#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("src_address0", 14, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("src_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("src_d0", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("src_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("src_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("src_address1", 14, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("src_ce1", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("src_d1", 32, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("src_q1", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("src_we1", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("dst_address0", 14, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("dst_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("dst_d0", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("dst_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("dst_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("dst_address1", 14, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("dst_ce1", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("dst_d1", 32, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("dst_q1", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("dst_we1", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("upperThresh", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("lowerThresh", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "canny";
