set SynModuleInfo {
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_40_1 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_40_1 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_40_1
    SUBMODULES {
      {MODELNAME dpu_keygen_flow_control_loop_pipe_sequential_init RTLNAME dpu_keygen_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME dpu_keygen_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_41_2 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_41_2 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_41_2}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_42_3_VITIS_LOOP_43_4 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_42_3_VITIS_LOOP_43_4 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_42_3_VITIS_LOOP_43_4}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_48_5_VITIS_LOOP_49_6 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_48_5_VITIS_LOOP_49_6 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_48_5_VITIS_LOOP_49_6}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_54_7 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_54_7 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_54_7}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_55_8 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_55_8 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_55_8}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_56_9 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_56_9 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_56_9}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_321_1 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_321_1 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_321_1}
  {SRCNAME shake_absorb.1_Pipeline_VITIS_LOOP_369_4 MODELNAME shake_absorb_1_Pipeline_VITIS_LOOP_369_4 RTLNAME dpu_keygen_shake_absorb_1_Pipeline_VITIS_LOOP_369_4}
  {SRCNAME KeccakF1600_StatePermute MODELNAME KeccakF1600_StatePermute RTLNAME dpu_keygen_KeccakF1600_StatePermute
    SUBMODULES {
      {MODELNAME dpu_keygen_KeccakF1600_StatePermute_KeccakF_RoundConstants_ROM_AUTO_1R RTLNAME dpu_keygen_KeccakF1600_StatePermute_KeccakF_RoundConstants_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME shake_absorb.1_Pipeline_VITIS_LOOP_376_5 MODELNAME shake_absorb_1_Pipeline_VITIS_LOOP_376_5 RTLNAME dpu_keygen_shake_absorb_1_Pipeline_VITIS_LOOP_376_5}
  {SRCNAME shake_absorb.1_Pipeline_VITIS_LOOP_383_6 MODELNAME shake_absorb_1_Pipeline_VITIS_LOOP_383_6 RTLNAME dpu_keygen_shake_absorb_1_Pipeline_VITIS_LOOP_383_6}
  {SRCNAME shake_absorb.1_Pipeline_VITIS_LOOP_385_7 MODELNAME shake_absorb_1_Pipeline_VITIS_LOOP_385_7 RTLNAME dpu_keygen_shake_absorb_1_Pipeline_VITIS_LOOP_385_7}
  {SRCNAME shake_absorb.1_Pipeline_VITIS_LOOP_12_1 MODELNAME shake_absorb_1_Pipeline_VITIS_LOOP_12_1 RTLNAME dpu_keygen_shake_absorb_1_Pipeline_VITIS_LOOP_12_1}
  {SRCNAME shake_absorb.1 MODELNAME shake_absorb_1 RTLNAME dpu_keygen_shake_absorb_1
    SUBMODULES {
      {MODELNAME dpu_keygen_shake_absorb_1_t_RAM_AUTO_1R1W RTLNAME dpu_keygen_shake_absorb_1_t_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME shake_squeeze.2 MODELNAME shake_squeeze_2 RTLNAME dpu_keygen_shake_squeeze_2}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_321_16 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_321_16 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_321_16}
  {SRCNAME shake_absorb_Pipeline_VITIS_LOOP_351_1 MODELNAME shake_absorb_Pipeline_VITIS_LOOP_351_1 RTLNAME dpu_keygen_shake_absorb_Pipeline_VITIS_LOOP_351_1}
  {SRCNAME shake_absorb_Pipeline_VITIS_LOOP_12_1 MODELNAME shake_absorb_Pipeline_VITIS_LOOP_12_1 RTLNAME dpu_keygen_shake_absorb_Pipeline_VITIS_LOOP_12_1}
  {SRCNAME shake_absorb_Pipeline_VITIS_LOOP_360_2 MODELNAME shake_absorb_Pipeline_VITIS_LOOP_360_2 RTLNAME dpu_keygen_shake_absorb_Pipeline_VITIS_LOOP_360_2}
  {SRCNAME shake_absorb_Pipeline_VITIS_LOOP_369_4 MODELNAME shake_absorb_Pipeline_VITIS_LOOP_369_4 RTLNAME dpu_keygen_shake_absorb_Pipeline_VITIS_LOOP_369_4}
  {SRCNAME shake_absorb_Pipeline_VITIS_LOOP_376_5 MODELNAME shake_absorb_Pipeline_VITIS_LOOP_376_5 RTLNAME dpu_keygen_shake_absorb_Pipeline_VITIS_LOOP_376_5}
  {SRCNAME shake_absorb_Pipeline_VITIS_LOOP_383_6 MODELNAME shake_absorb_Pipeline_VITIS_LOOP_383_6 RTLNAME dpu_keygen_shake_absorb_Pipeline_VITIS_LOOP_383_6}
  {SRCNAME shake_absorb_Pipeline_VITIS_LOOP_385_7 MODELNAME shake_absorb_Pipeline_VITIS_LOOP_385_7 RTLNAME dpu_keygen_shake_absorb_Pipeline_VITIS_LOOP_385_7}
  {SRCNAME shake_absorb_Pipeline_VITIS_LOOP_12_12 MODELNAME shake_absorb_Pipeline_VITIS_LOOP_12_12 RTLNAME dpu_keygen_shake_absorb_Pipeline_VITIS_LOOP_12_12}
  {SRCNAME shake_absorb MODELNAME shake_absorb RTLNAME dpu_keygen_shake_absorb
    SUBMODULES {
      {MODELNAME dpu_keygen_shake_absorb_t_RAM_AUTO_1R1W RTLNAME dpu_keygen_shake_absorb_t_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_417_2 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_417_2 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_417_2}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_503_2 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_503_2 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_503_2}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_95_1 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_95_1 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_95_1}
  {SRCNAME sample_eta_Pipeline_VITIS_LOOP_417_2 MODELNAME sample_eta_Pipeline_VITIS_LOOP_417_2 RTLNAME dpu_keygen_sample_eta_Pipeline_VITIS_LOOP_417_2}
  {SRCNAME sample_eta_Pipeline_VITIS_LOOP_533_2 MODELNAME sample_eta_Pipeline_VITIS_LOOP_533_2 RTLNAME dpu_keygen_sample_eta_Pipeline_VITIS_LOOP_533_2}
  {SRCNAME sample_eta MODELNAME sample_eta RTLNAME dpu_keygen_sample_eta
    SUBMODULES {
      {MODELNAME dpu_keygen_sample_eta_buf_RAM_AUTO_1R1W RTLNAME dpu_keygen_sample_eta_buf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_95_17 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_95_17 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_95_17}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_95_18 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_95_18 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_95_18}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_95_19 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_95_19 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_95_19}
  {SRCNAME read_p2 MODELNAME read_p2 RTLNAME dpu_keygen_read_p2}
  {SRCNAME read_p1 MODELNAME read_p1 RTLNAME dpu_keygen_read_p1}
  {SRCNAME dpu_unit MODELNAME dpu_unit RTLNAME dpu_keygen_dpu_unit
    SUBMODULES {
      {MODELNAME dpu_keygen_mul_32s_32s_64_1_0 RTLNAME dpu_keygen_mul_32s_32s_64_1_0 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME write_p3 MODELNAME write_p3 RTLNAME dpu_keygen_write_p3}
  {SRCNAME write_p4 MODELNAME write_p4 RTLNAME dpu_keygen_write_p4}
  {SRCNAME dpu_func_Pipeline_FUNC_NTT_LOOP1 MODELNAME dpu_func_Pipeline_FUNC_NTT_LOOP1 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_NTT_LOOP1}
  {SRCNAME dpu_func_Pipeline_FUNC_NTT_LOOP2 MODELNAME dpu_func_Pipeline_FUNC_NTT_LOOP2 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_NTT_LOOP2}
  {SRCNAME dpu_func_Pipeline_FUNC_NTT_LOOP3 MODELNAME dpu_func_Pipeline_FUNC_NTT_LOOP3 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_NTT_LOOP3}
  {SRCNAME dpu_func_Pipeline_FUNC_NTT_LOOP4 MODELNAME dpu_func_Pipeline_FUNC_NTT_LOOP4 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_NTT_LOOP4}
  {SRCNAME read_ntt MODELNAME read_ntt RTLNAME dpu_keygen_read_ntt}
  {SRCNAME dpu_func_Pipeline_FUNC_NTT_LOOP5 MODELNAME dpu_func_Pipeline_FUNC_NTT_LOOP5 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_NTT_LOOP5}
  {SRCNAME dpu_func_Pipeline_FUNC_POW2ROUND_LOOP1 MODELNAME dpu_func_Pipeline_FUNC_POW2ROUND_LOOP1 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_POW2ROUND_LOOP1}
  {SRCNAME dpu_func_Pipeline_FUNC_CADDQ_LOOP1 MODELNAME dpu_func_Pipeline_FUNC_CADDQ_LOOP1 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_CADDQ_LOOP1}
  {SRCNAME dpu_func_Pipeline_FUNC_MATMUL_LOOP1 MODELNAME dpu_func_Pipeline_FUNC_MATMUL_LOOP1 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_MATMUL_LOOP1}
  {SRCNAME dpu_func_Pipeline_FUNC_MATMUL_LOOP2 MODELNAME dpu_func_Pipeline_FUNC_MATMUL_LOOP2 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_MATMUL_LOOP2}
  {SRCNAME dpu_func_Pipeline_FUNC_MATMUL_LOOP3 MODELNAME dpu_func_Pipeline_FUNC_MATMUL_LOOP3 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_MATMUL_LOOP3}
  {SRCNAME dpu_func_Pipeline_FUNC_MATMUL_LOOP4 MODELNAME dpu_func_Pipeline_FUNC_MATMUL_LOOP4 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_MATMUL_LOOP4}
  {SRCNAME dpu_func_Pipeline_FUNC_MATMUL_LOOP5 MODELNAME dpu_func_Pipeline_FUNC_MATMUL_LOOP5 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_MATMUL_LOOP5}
  {SRCNAME dpu_func_Pipeline_FUNC_MONTMUL_LOOP1 MODELNAME dpu_func_Pipeline_FUNC_MONTMUL_LOOP1 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_MONTMUL_LOOP1}
  {SRCNAME dpu_func_Pipeline_FUNC_MONTMUL_LOOP2 MODELNAME dpu_func_Pipeline_FUNC_MONTMUL_LOOP2 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_MONTMUL_LOOP2}
  {SRCNAME dpu_func_Pipeline_FUNC_MONTMUL_LOOP3 MODELNAME dpu_func_Pipeline_FUNC_MONTMUL_LOOP3 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_MONTMUL_LOOP3}
  {SRCNAME dpu_func_Pipeline_FUNC_MONTMUL_LOOP4 MODELNAME dpu_func_Pipeline_FUNC_MONTMUL_LOOP4 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_MONTMUL_LOOP4}
  {SRCNAME dpu_func_Pipeline_FUNC_RD_LOOP1 MODELNAME dpu_func_Pipeline_FUNC_RD_LOOP1 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_RD_LOOP1}
  {SRCNAME dpu_func_Pipeline_FUNC_RD_LOOP2 MODELNAME dpu_func_Pipeline_FUNC_RD_LOOP2 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_RD_LOOP2}
  {SRCNAME dpu_func_Pipeline_FUNC_RD_LOOP3 MODELNAME dpu_func_Pipeline_FUNC_RD_LOOP3 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_RD_LOOP3}
  {SRCNAME dpu_func_Pipeline_FUNC_SUB_LOOP1 MODELNAME dpu_func_Pipeline_FUNC_SUB_LOOP1 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_SUB_LOOP1}
  {SRCNAME read_intt MODELNAME read_intt RTLNAME dpu_keygen_read_intt}
  {SRCNAME dpu_func_Pipeline_FUNC_INTT_LOOP1 MODELNAME dpu_func_Pipeline_FUNC_INTT_LOOP1 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_INTT_LOOP1}
  {SRCNAME dpu_func_Pipeline_FUNC_INTT_LOOP2 MODELNAME dpu_func_Pipeline_FUNC_INTT_LOOP2 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_INTT_LOOP2}
  {SRCNAME dpu_func_Pipeline_FUNC_INTT_LOOP3 MODELNAME dpu_func_Pipeline_FUNC_INTT_LOOP3 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_INTT_LOOP3}
  {SRCNAME dpu_func_Pipeline_FUNC_INTT_LOOP4 MODELNAME dpu_func_Pipeline_FUNC_INTT_LOOP4 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_INTT_LOOP4}
  {SRCNAME dpu_func_Pipeline_FUNC_INTT_LOOP5 MODELNAME dpu_func_Pipeline_FUNC_INTT_LOOP5 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_INTT_LOOP5}
  {SRCNAME dpu_func_Pipeline_FUNC_ADD_LOOP1 MODELNAME dpu_func_Pipeline_FUNC_ADD_LOOP1 RTLNAME dpu_keygen_dpu_func_Pipeline_FUNC_ADD_LOOP1}
  {SRCNAME dpu_func MODELNAME dpu_func RTLNAME dpu_keygen_dpu_func}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_55_5 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_55_5 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_55_5}
  {SRCNAME dpu_pack_Pipeline_VITIS_LOOP_73_1 MODELNAME dpu_pack_Pipeline_VITIS_LOOP_73_1 RTLNAME dpu_keygen_dpu_pack_Pipeline_VITIS_LOOP_73_1}
  {SRCNAME dpu_pack_Pipeline_VITIS_LOOP_605_2 MODELNAME dpu_pack_Pipeline_VITIS_LOOP_605_2 RTLNAME dpu_keygen_dpu_pack_Pipeline_VITIS_LOOP_605_2}
  {SRCNAME dpu_pack MODELNAME dpu_pack RTLNAME dpu_keygen_dpu_pack}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_321_110 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_321_110 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_321_110}
  {SRCNAME shake_absorb.3_Pipeline_VITIS_LOOP_369_4 MODELNAME shake_absorb_3_Pipeline_VITIS_LOOP_369_4 RTLNAME dpu_keygen_shake_absorb_3_Pipeline_VITIS_LOOP_369_4}
  {SRCNAME shake_absorb.3_Pipeline_VITIS_LOOP_376_5 MODELNAME shake_absorb_3_Pipeline_VITIS_LOOP_376_5 RTLNAME dpu_keygen_shake_absorb_3_Pipeline_VITIS_LOOP_376_5}
  {SRCNAME shake_absorb.3 MODELNAME shake_absorb_3 RTLNAME dpu_keygen_shake_absorb_3}
  {SRCNAME shake_squeeze MODELNAME shake_squeeze RTLNAME dpu_keygen_shake_squeeze}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_60_6 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_60_6 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_60_6}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_61_7 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_61_7 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_61_7}
  {SRCNAME dpu_keygen_Pipeline_VITIS_LOOP_62_8 MODELNAME dpu_keygen_Pipeline_VITIS_LOOP_62_8 RTLNAME dpu_keygen_dpu_keygen_Pipeline_VITIS_LOOP_62_8}
  {SRCNAME dpu_pack.4_Pipeline_VITIS_LOOP_666_8 MODELNAME dpu_pack_4_Pipeline_VITIS_LOOP_666_8 RTLNAME dpu_keygen_dpu_pack_4_Pipeline_VITIS_LOOP_666_8}
  {SRCNAME dpu_pack.4_Pipeline_VITIS_LOOP_91_1 MODELNAME dpu_pack_4_Pipeline_VITIS_LOOP_91_1 RTLNAME dpu_keygen_dpu_pack_4_Pipeline_VITIS_LOOP_91_1}
  {SRCNAME dpu_pack.4_Pipeline_VITIS_LOOP_73_13 MODELNAME dpu_pack_4_Pipeline_VITIS_LOOP_73_13 RTLNAME dpu_keygen_dpu_pack_4_Pipeline_VITIS_LOOP_73_13}
  {SRCNAME dpu_pack.4_Pipeline_VITIS_LOOP_693_10 MODELNAME dpu_pack_4_Pipeline_VITIS_LOOP_693_10 RTLNAME dpu_keygen_dpu_pack_4_Pipeline_VITIS_LOOP_693_10}
  {SRCNAME dpu_pack.4_Pipeline_VITIS_LOOP_73_15 MODELNAME dpu_pack_4_Pipeline_VITIS_LOOP_73_15 RTLNAME dpu_keygen_dpu_pack_4_Pipeline_VITIS_LOOP_73_15}
  {SRCNAME dpu_pack.4_Pipeline_VITIS_LOOP_723_14 MODELNAME dpu_pack_4_Pipeline_VITIS_LOOP_723_14 RTLNAME dpu_keygen_dpu_pack_4_Pipeline_VITIS_LOOP_723_14}
  {SRCNAME dpu_pack.4_Pipeline_VITIS_LOOP_709_12 MODELNAME dpu_pack_4_Pipeline_VITIS_LOOP_709_12 RTLNAME dpu_keygen_dpu_pack_4_Pipeline_VITIS_LOOP_709_12}
  {SRCNAME dpu_pack.4_Pipeline_VITIS_LOOP_91_14 MODELNAME dpu_pack_4_Pipeline_VITIS_LOOP_91_14 RTLNAME dpu_keygen_dpu_pack_4_Pipeline_VITIS_LOOP_91_14}
  {SRCNAME dpu_pack.4_Pipeline_VITIS_LOOP_73_1 MODELNAME dpu_pack_4_Pipeline_VITIS_LOOP_73_1 RTLNAME dpu_keygen_dpu_pack_4_Pipeline_VITIS_LOOP_73_1}
  {SRCNAME dpu_pack.4_Pipeline_VITIS_LOOP_630_6 MODELNAME dpu_pack_4_Pipeline_VITIS_LOOP_630_6 RTLNAME dpu_keygen_dpu_pack_4_Pipeline_VITIS_LOOP_630_6}
  {SRCNAME dpu_pack.4 MODELNAME dpu_pack_4 RTLNAME dpu_keygen_dpu_pack_4}
  {SRCNAME dpu_keygen MODELNAME dpu_keygen RTLNAME dpu_keygen IS_TOP 1
    SUBMODULES {
      {MODELNAME dpu_keygen_zetas_ROM_AUTO_1R RTLNAME dpu_keygen_zetas_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME dpu_keygen_buf_RAM_AUTO_1R1W RTLNAME dpu_keygen_buf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME dpu_keygen_dpu_pMem_RAM_T2P_BRAM_1R1W RTLNAME dpu_keygen_dpu_pMem_RAM_T2P_BRAM_1R1W BINDTYPE storage TYPE ram_t2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME dpu_keygen_spu_s_RAM_AUTO_1R1W RTLNAME dpu_keygen_spu_s_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME dpu_keygen_tmp1_RAM_AUTO_1R1W RTLNAME dpu_keygen_tmp1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME dpu_keygen_tmp2_RAM_AUTO_1R1W RTLNAME dpu_keygen_tmp2_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME dpu_keygen_tr_RAM_AUTO_1R1W RTLNAME dpu_keygen_tr_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
}
