// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cordiccart2pol_cordiccart2pol,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=1000.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.873750,HLS_SYN_LAT=14,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=780,HLS_SYN_LUT=1597,HLS_VERSION=2022_1}" *)

module cordiccart2pol (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        y,
        r,
        r_ap_vld,
        theta,
        theta_ap_vld
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [14:0] x;
input  [14:0] y;
output  [14:0] r;
output   r_ap_vld;
output  [14:0] theta;
output   theta_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg r_ap_vld;
reg theta_ap_vld;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_fu_148_p3;
reg   [0:0] tmp_reg_1203;
wire   [14:0] x_cordic_V_35_fu_168_p3;
reg   [14:0] x_cordic_V_35_reg_1208;
wire   [14:0] y_cordic_V_32_fu_176_p3;
reg   [14:0] y_cordic_V_32_reg_1215;
reg   [0:0] tmp_1_reg_1222;
reg   [0:0] tmp_2_reg_1228;
wire   [14:0] x_cordic_V_4_fu_212_p3;
reg   [14:0] x_cordic_V_4_reg_1234;
wire    ap_CS_fsm_state2;
wire   [14:0] y_cordic_V_4_fu_219_p3;
reg   [14:0] y_cordic_V_4_reg_1240;
reg   [13:0] r_V_22_reg_1246;
reg   [13:0] r_V_23_reg_1251;
reg   [0:0] tmp_3_reg_1256;
wire   [14:0] x_cordic_V_7_fu_280_p3;
reg   [14:0] x_cordic_V_7_reg_1263;
wire    ap_CS_fsm_state3;
wire   [14:0] y_cordic_V_7_fu_287_p3;
reg   [14:0] y_cordic_V_7_reg_1269;
reg   [12:0] r_V_24_reg_1275;
reg   [12:0] r_V_25_reg_1280;
reg   [0:0] tmp_4_reg_1285;
reg   [0:0] tmp_5_reg_1291;
wire   [14:0] x_cordic_V_10_fu_356_p3;
reg   [14:0] x_cordic_V_10_reg_1296;
wire    ap_CS_fsm_state4;
wire   [14:0] y_cordic_V_10_fu_363_p3;
reg   [14:0] y_cordic_V_10_reg_1302;
reg   [11:0] r_V_26_reg_1308;
reg   [11:0] r_V_27_reg_1313;
reg   [0:0] tmp_6_reg_1318;
reg   [0:0] tmp_7_reg_1324;
wire   [14:0] x_cordic_V_13_fu_432_p3;
reg   [14:0] x_cordic_V_13_reg_1329;
wire    ap_CS_fsm_state5;
wire   [14:0] y_cordic_V_13_fu_439_p3;
reg   [14:0] y_cordic_V_13_reg_1335;
reg   [10:0] r_V_28_reg_1342;
reg   [10:0] r_V_29_reg_1347;
reg   [0:0] tmp_8_reg_1352;
wire   [14:0] y_cordic_V_14_fu_485_p2;
reg   [14:0] y_cordic_V_14_reg_1358;
wire    ap_CS_fsm_state6;
wire   [14:0] y_cordic_V_15_fu_495_p2;
reg   [14:0] y_cordic_V_15_reg_1363;
wire   [14:0] x_cordic_V_16_fu_500_p3;
reg   [14:0] x_cordic_V_16_reg_1368;
reg   [9:0] r_V_31_reg_1374;
reg   [0:0] tmp_10_reg_1379;
wire    ap_CS_fsm_state7;
wire   [14:0] x_cordic_V_17_fu_562_p2;
reg   [14:0] x_cordic_V_17_reg_1385;
wire   [14:0] y_cordic_V_17_fu_567_p2;
reg   [14:0] y_cordic_V_17_reg_1390;
wire   [14:0] x_cordic_V_18_fu_573_p2;
reg   [14:0] x_cordic_V_18_reg_1395;
wire   [14:0] y_cordic_V_18_fu_578_p2;
reg   [14:0] y_cordic_V_18_reg_1400;
wire   [9:0] add_ln36_5_fu_600_p2;
reg   [9:0] add_ln36_5_reg_1405;
reg   [0:0] tmp_12_reg_1410;
wire    ap_CS_fsm_state8;
wire   [14:0] x_cordic_V_20_fu_652_p2;
reg   [14:0] x_cordic_V_20_reg_1416;
wire   [14:0] y_cordic_V_20_fu_658_p2;
reg   [14:0] y_cordic_V_20_reg_1421;
wire   [14:0] x_cordic_V_21_fu_664_p2;
reg   [14:0] x_cordic_V_21_reg_1426;
wire   [14:0] y_cordic_V_21_fu_670_p2;
reg   [14:0] y_cordic_V_21_reg_1431;
reg   [0:0] tmp_13_reg_1436;
reg   [0:0] tmp_14_reg_1441;
wire    ap_CS_fsm_state9;
wire   [14:0] x_cordic_V_23_fu_730_p2;
reg   [14:0] x_cordic_V_23_reg_1447;
wire   [14:0] y_cordic_V_23_fu_736_p2;
reg   [14:0] y_cordic_V_23_reg_1452;
wire   [14:0] x_cordic_V_24_fu_742_p2;
reg   [14:0] x_cordic_V_24_reg_1457;
wire   [14:0] y_cordic_V_24_fu_748_p2;
reg   [14:0] y_cordic_V_24_reg_1462;
reg   [0:0] tmp_15_reg_1467;
reg   [0:0] tmp_16_reg_1472;
wire    ap_CS_fsm_state10;
wire   [14:0] x_cordic_V_26_fu_808_p2;
reg   [14:0] x_cordic_V_26_reg_1478;
wire   [14:0] y_cordic_V_26_fu_814_p2;
reg   [14:0] y_cordic_V_26_reg_1483;
wire   [14:0] x_cordic_V_27_fu_820_p2;
reg   [14:0] x_cordic_V_27_reg_1488;
wire   [14:0] y_cordic_V_27_fu_826_p2;
reg   [14:0] y_cordic_V_27_reg_1493;
reg   [0:0] tmp_17_reg_1498;
reg   [0:0] tmp_18_reg_1503;
wire    ap_CS_fsm_state11;
wire   [14:0] x_cordic_V_29_fu_886_p2;
reg   [14:0] x_cordic_V_29_reg_1509;
wire   [14:0] y_cordic_V_29_fu_892_p2;
reg   [14:0] y_cordic_V_29_reg_1514;
wire   [14:0] x_cordic_V_30_fu_898_p2;
reg   [14:0] x_cordic_V_30_reg_1519;
wire   [14:0] y_cordic_V_30_fu_904_p2;
reg   [14:0] y_cordic_V_30_reg_1524;
reg   [0:0] tmp_19_reg_1529;
wire   [13:0] theta_out_V_2_fu_932_p3;
reg   [13:0] theta_out_V_2_reg_1534;
wire    ap_CS_fsm_state12;
wire   [13:0] select_ln1697_fu_939_p3;
reg   [13:0] select_ln1697_reg_1539;
wire   [10:0] select_ln1697_4_fu_946_p3;
reg   [10:0] select_ln1697_4_reg_1544;
wire   [7:0] select_ln1697_13_fu_953_p3;
reg   [7:0] select_ln1697_13_reg_1549;
wire   [13:0] select_ln1697_16_fu_960_p3;
reg   [13:0] select_ln1697_16_reg_1554;
wire   [7:0] select_ln1697_19_fu_967_p3;
reg   [7:0] select_ln1697_19_reg_1559;
wire   [7:0] select_ln1697_22_fu_974_p3;
reg   [7:0] select_ln1697_22_reg_1564;
reg   [0:0] tmp_20_reg_1569;
wire   [14:0] x_cordic_V_32_fu_1013_p2;
reg   [14:0] x_cordic_V_32_reg_1574;
wire   [14:0] x_cordic_V_33_fu_1019_p2;
reg   [14:0] x_cordic_V_33_reg_1579;
wire   [10:0] select_ln36_fu_1033_p3;
reg   [10:0] select_ln36_reg_1584;
wire   [7:0] add_ln36_1_fu_1045_p2;
reg   [7:0] add_ln36_1_reg_1589;
wire    ap_CS_fsm_state13;
wire   [13:0] add_ln36_3_fu_1054_p2;
reg   [13:0] add_ln36_3_reg_1594;
wire   [10:0] add_ln36_7_fu_1067_p2;
reg   [10:0] add_ln36_7_reg_1599;
reg   [8:0] r_3_reg_1604;
reg   [5:0] r_V_reg_1609;
wire   [14:0] add_ln1394_fu_1125_p2;
reg   [14:0] add_ln1394_reg_1614;
wire   [13:0] theta_out_V_3_fu_1142_p2;
reg   [13:0] theta_out_V_3_reg_1619;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire   [14:0] x_cordic_V_fu_156_p2;
wire   [14:0] y_cordic_V_fu_162_p2;
wire   [14:0] x_cordic_V_3_fu_208_p2;
wire   [14:0] x_cordic_V_36_fu_200_p2;
wire   [14:0] y_cordic_V_2_fu_204_p2;
wire  signed [14:0] sext_ln1534_fu_254_p1;
wire  signed [14:0] sext_ln1534_1_fu_257_p1;
wire   [14:0] x_cordic_V_6_fu_270_p2;
wire   [14:0] x_cordic_V_5_fu_260_p2;
wire   [14:0] y_cordic_V_6_fu_275_p2;
wire   [14:0] y_cordic_V_5_fu_265_p2;
wire  signed [14:0] sext_ln1534_2_fu_330_p1;
wire  signed [14:0] sext_ln1534_3_fu_333_p1;
wire   [14:0] x_cordic_V_9_fu_346_p2;
wire   [14:0] x_cordic_V_8_fu_336_p2;
wire   [14:0] y_cordic_V_9_fu_351_p2;
wire   [14:0] y_cordic_V_8_fu_341_p2;
wire  signed [14:0] sext_ln1534_4_fu_406_p1;
wire  signed [14:0] sext_ln1534_5_fu_409_p1;
wire   [14:0] x_cordic_V_12_fu_422_p2;
wire   [14:0] x_cordic_V_11_fu_412_p2;
wire   [14:0] y_cordic_V_12_fu_427_p2;
wire   [14:0] y_cordic_V_11_fu_417_p2;
wire  signed [14:0] sext_ln1534_6_fu_474_p1;
wire  signed [14:0] sext_ln1534_7_fu_477_p1;
wire   [14:0] x_cordic_V_15_fu_490_p2;
wire   [14:0] x_cordic_V_14_fu_480_p2;
wire   [0:0] tmp_9_fu_517_p3;
wire   [14:0] y_cordic_V_16_fu_532_p3;
wire   [9:0] r_V_30_fu_537_p4;
wire  signed [14:0] sext_ln1534_8_fu_547_p1;
wire  signed [14:0] sext_ln1534_9_fu_551_p1;
wire   [0:0] tmp_11_fu_584_p3;
wire   [9:0] select_ln1697_10_fu_592_p3;
wire   [9:0] select_ln1697_7_fu_524_p3;
wire   [14:0] y_cordic_V_19_fu_611_p3;
wire   [8:0] r_V_32_fu_616_p4;
wire   [14:0] x_cordic_V_19_fu_606_p3;
wire   [8:0] r_V_33_fu_630_p4;
wire  signed [14:0] sext_ln1534_10_fu_626_p1;
wire  signed [14:0] sext_ln1534_11_fu_640_p1;
wire   [14:0] y_cordic_V_22_fu_689_p3;
wire   [7:0] r_V_34_fu_694_p4;
wire   [14:0] x_cordic_V_22_fu_684_p3;
wire   [7:0] r_V_35_fu_708_p4;
wire  signed [14:0] sext_ln1534_12_fu_704_p1;
wire  signed [14:0] sext_ln1534_13_fu_718_p1;
wire   [14:0] y_cordic_V_25_fu_767_p3;
wire   [6:0] r_V_36_fu_772_p4;
wire   [14:0] x_cordic_V_25_fu_762_p3;
wire   [6:0] r_V_37_fu_786_p4;
wire  signed [14:0] sext_ln1534_14_fu_782_p1;
wire  signed [14:0] sext_ln1534_15_fu_796_p1;
wire   [14:0] y_cordic_V_28_fu_845_p3;
wire   [5:0] r_V_38_fu_850_p4;
wire   [14:0] x_cordic_V_28_fu_840_p3;
wire   [5:0] r_V_39_fu_864_p4;
wire  signed [14:0] sext_ln1534_16_fu_860_p1;
wire  signed [14:0] sext_ln1534_17_fu_874_p1;
wire   [13:0] theta_out_V_1_fu_925_p3;
wire   [13:0] theta_out_V_fu_918_p3;
wire   [14:0] y_cordic_V_31_fu_986_p3;
wire   [4:0] r_V_40_fu_991_p4;
wire   [14:0] x_cordic_V_31_fu_981_p3;
wire  signed [14:0] sext_ln1534_18_fu_1001_p1;
wire   [0:0] tmp_21_fu_1025_p3;
wire   [7:0] add_ln36_fu_1041_p2;
wire   [13:0] add_ln36_2_fu_1050_p2;
wire  signed [10:0] sext_ln36_1_fu_1059_p1;
wire   [10:0] add_ln36_6_fu_1062_p2;
wire   [14:0] x_cordic_V_34_fu_1072_p3;
wire   [13:0] r_1_fu_1077_p4;
wire   [11:0] r_2_fu_1091_p4;
wire  signed [14:0] sext_ln1534_19_fu_1087_p1;
wire  signed [14:0] sext_ln1534_20_fu_1101_p1;
wire  signed [13:0] sext_ln36_fu_1131_p1;
wire   [13:0] zext_ln36_fu_1139_p1;
wire   [13:0] add_ln36_4_fu_1134_p2;
wire  signed [14:0] sext_ln1534_22_fu_1151_p1;
wire   [14:0] sub_ln1394_fu_1154_p2;
wire  signed [14:0] sext_ln1534_21_fu_1148_p1;
wire   [0:0] tmp_22_fu_1169_p3;
wire   [14:0] select_ln55_fu_1176_p3;
wire  signed [14:0] sext_ln36_2_fu_1166_p1;
wire   [14:0] add_ln55_fu_1184_p2;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        add_ln1394_reg_1614 <= add_ln1394_fu_1125_p2;
        add_ln36_1_reg_1589[7 : 4] <= add_ln36_1_fu_1045_p2[7 : 4];
        add_ln36_3_reg_1594[13 : 1] <= add_ln36_3_fu_1054_p2[13 : 1];
        add_ln36_7_reg_1599[10 : 1] <= add_ln36_7_fu_1067_p2[10 : 1];
        r_3_reg_1604 <= {{x_cordic_V_34_fu_1072_p3[14:6]}};
        r_V_reg_1609 <= {{x_cordic_V_34_fu_1072_p3[14:9]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln36_5_reg_1405[9 : 8] <= add_ln36_5_fu_600_p2[9 : 8];
        tmp_10_reg_1379 <= y_cordic_V_16_fu_532_p3[32'd14];
        x_cordic_V_17_reg_1385 <= x_cordic_V_17_fu_562_p2;
        x_cordic_V_18_reg_1395 <= x_cordic_V_18_fu_573_p2;
        y_cordic_V_17_reg_1390 <= y_cordic_V_17_fu_567_p2;
        y_cordic_V_18_reg_1400 <= y_cordic_V_18_fu_578_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        r_V_22_reg_1246 <= {{y_cordic_V_4_fu_219_p3[14:1]}};
        r_V_23_reg_1251 <= {{x_cordic_V_4_fu_212_p3[14:1]}};
        tmp_3_reg_1256 <= y_cordic_V_4_fu_219_p3[32'd14];
        x_cordic_V_4_reg_1234 <= x_cordic_V_4_fu_212_p3;
        y_cordic_V_4_reg_1240 <= y_cordic_V_4_fu_219_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        r_V_24_reg_1275 <= {{y_cordic_V_7_fu_287_p3[14:2]}};
        r_V_25_reg_1280 <= {{x_cordic_V_7_fu_280_p3[14:2]}};
        tmp_4_reg_1285 <= y_cordic_V_7_fu_287_p3[32'd14];
        tmp_5_reg_1291 <= y_cordic_V_7_fu_287_p3[32'd14];
        x_cordic_V_7_reg_1263 <= x_cordic_V_7_fu_280_p3;
        y_cordic_V_7_reg_1269 <= y_cordic_V_7_fu_287_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        r_V_26_reg_1308 <= {{y_cordic_V_10_fu_363_p3[14:3]}};
        r_V_27_reg_1313 <= {{x_cordic_V_10_fu_356_p3[14:3]}};
        tmp_6_reg_1318 <= y_cordic_V_10_fu_363_p3[32'd14];
        tmp_7_reg_1324 <= y_cordic_V_10_fu_363_p3[32'd14];
        x_cordic_V_10_reg_1296 <= x_cordic_V_10_fu_356_p3;
        y_cordic_V_10_reg_1302 <= y_cordic_V_10_fu_363_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        r_V_28_reg_1342 <= {{y_cordic_V_13_fu_439_p3[14:4]}};
        r_V_29_reg_1347 <= {{x_cordic_V_13_fu_432_p3[14:4]}};
        tmp_8_reg_1352 <= y_cordic_V_13_fu_439_p3[32'd14];
        x_cordic_V_13_reg_1329 <= x_cordic_V_13_fu_432_p3;
        y_cordic_V_13_reg_1335 <= y_cordic_V_13_fu_439_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        r_V_31_reg_1374 <= {{x_cordic_V_16_fu_500_p3[14:5]}};
        x_cordic_V_16_reg_1368 <= x_cordic_V_16_fu_500_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        select_ln1697_13_reg_1549[7] <= select_ln1697_13_fu_953_p3[7];
        select_ln1697_16_reg_1554[13 : 6] <= select_ln1697_16_fu_960_p3[13 : 6];
        select_ln1697_19_reg_1559[7 : 5] <= select_ln1697_19_fu_967_p3[7 : 5];
        select_ln1697_22_reg_1564[7 : 4] <= select_ln1697_22_fu_974_p3[7 : 4];
        select_ln1697_4_reg_1544[2 : 1] <= select_ln1697_4_fu_946_p3[2 : 1];
select_ln1697_4_reg_1544[10] <= select_ln1697_4_fu_946_p3[10];
        select_ln1697_reg_1539[1] <= select_ln1697_fu_939_p3[1];
select_ln1697_reg_1539[3] <= select_ln1697_fu_939_p3[3];
select_ln1697_reg_1539[5] <= select_ln1697_fu_939_p3[5];
select_ln1697_reg_1539[13 : 11] <= select_ln1697_fu_939_p3[13 : 11];
        select_ln36_reg_1584[3] <= select_ln36_fu_1033_p3[3];
        theta_out_V_2_reg_1534[13 : 1] <= theta_out_V_2_fu_932_p3[13 : 1];
        tmp_20_reg_1569 <= y_cordic_V_31_fu_986_p3[32'd14];
        x_cordic_V_32_reg_1574 <= x_cordic_V_32_fu_1013_p2;
        x_cordic_V_33_reg_1579 <= x_cordic_V_33_fu_1019_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        theta_out_V_3_reg_1619[13 : 1] <= theta_out_V_3_fu_1142_p2[13 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        tmp_12_reg_1410 <= y_cordic_V_19_fu_611_p3[32'd14];
        tmp_13_reg_1436 <= y_cordic_V_19_fu_611_p3[32'd14];
        x_cordic_V_20_reg_1416 <= x_cordic_V_20_fu_652_p2;
        x_cordic_V_21_reg_1426 <= x_cordic_V_21_fu_664_p2;
        y_cordic_V_20_reg_1421 <= y_cordic_V_20_fu_658_p2;
        y_cordic_V_21_reg_1431 <= y_cordic_V_21_fu_670_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp_14_reg_1441 <= y_cordic_V_22_fu_689_p3[32'd14];
        tmp_15_reg_1467 <= y_cordic_V_22_fu_689_p3[32'd14];
        x_cordic_V_23_reg_1447 <= x_cordic_V_23_fu_730_p2;
        x_cordic_V_24_reg_1457 <= x_cordic_V_24_fu_742_p2;
        y_cordic_V_23_reg_1452 <= y_cordic_V_23_fu_736_p2;
        y_cordic_V_24_reg_1462 <= y_cordic_V_24_fu_748_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_16_reg_1472 <= y_cordic_V_25_fu_767_p3[32'd14];
        tmp_17_reg_1498 <= y_cordic_V_25_fu_767_p3[32'd14];
        x_cordic_V_26_reg_1478 <= x_cordic_V_26_fu_808_p2;
        x_cordic_V_27_reg_1488 <= x_cordic_V_27_fu_820_p2;
        y_cordic_V_26_reg_1483 <= y_cordic_V_26_fu_814_p2;
        y_cordic_V_27_reg_1493 <= y_cordic_V_27_fu_826_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        tmp_18_reg_1503 <= y_cordic_V_28_fu_845_p3[32'd14];
        tmp_19_reg_1529 <= y_cordic_V_28_fu_845_p3[32'd14];
        x_cordic_V_29_reg_1509 <= x_cordic_V_29_fu_886_p2;
        x_cordic_V_30_reg_1519 <= x_cordic_V_30_fu_898_p2;
        y_cordic_V_29_reg_1514 <= y_cordic_V_29_fu_892_p2;
        y_cordic_V_30_reg_1524 <= y_cordic_V_30_fu_904_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_1_reg_1222 <= y_cordic_V_32_fu_176_p3[32'd14];
        tmp_2_reg_1228 <= y_cordic_V_32_fu_176_p3[32'd14];
        tmp_reg_1203 <= x[32'd14];
        x_cordic_V_35_reg_1208 <= x_cordic_V_35_fu_168_p3;
        y_cordic_V_32_reg_1215 <= y_cordic_V_32_fu_176_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (tmp_8_reg_1352 == 1'd0))) begin
        y_cordic_V_14_reg_1358 <= y_cordic_V_14_fu_485_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (tmp_8_reg_1352 == 1'd1))) begin
        y_cordic_V_15_reg_1363 <= y_cordic_V_15_fu_495_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        r_ap_vld = 1'b1;
    end else begin
        r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        theta_ap_vld = 1'b1;
    end else begin
        theta_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1394_fu_1125_p2 = ($signed(sext_ln1534_19_fu_1087_p1) + $signed(sext_ln1534_20_fu_1101_p1));

assign add_ln36_1_fu_1045_p2 = (add_ln36_fu_1041_p2 + select_ln1697_22_reg_1564);

assign add_ln36_2_fu_1050_p2 = (theta_out_V_2_reg_1534 + select_ln1697_reg_1539);

assign add_ln36_3_fu_1054_p2 = (add_ln36_2_fu_1050_p2 + select_ln1697_16_reg_1554);

assign add_ln36_4_fu_1134_p2 = ($signed(add_ln36_3_reg_1594) + $signed(sext_ln36_fu_1131_p1));

assign add_ln36_5_fu_600_p2 = (select_ln1697_10_fu_592_p3 + select_ln1697_7_fu_524_p3);

assign add_ln36_6_fu_1062_p2 = ($signed(sext_ln36_1_fu_1059_p1) + $signed(select_ln1697_4_reg_1544));

assign add_ln36_7_fu_1067_p2 = (select_ln36_reg_1584 + add_ln36_6_fu_1062_p2);

assign add_ln36_fu_1041_p2 = (select_ln1697_13_reg_1549 + select_ln1697_19_reg_1559);

assign add_ln55_fu_1184_p2 = ($signed(select_ln55_fu_1176_p3) + $signed(sext_ln36_2_fu_1166_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign r = ($signed(sub_ln1394_fu_1154_p2) - $signed(sext_ln1534_21_fu_1148_p1));

assign r_1_fu_1077_p4 = {{x_cordic_V_34_fu_1072_p3[14:1]}};

assign r_2_fu_1091_p4 = {{x_cordic_V_34_fu_1072_p3[14:3]}};

assign r_V_30_fu_537_p4 = {{y_cordic_V_16_fu_532_p3[14:5]}};

assign r_V_32_fu_616_p4 = {{y_cordic_V_19_fu_611_p3[14:6]}};

assign r_V_33_fu_630_p4 = {{x_cordic_V_19_fu_606_p3[14:6]}};

assign r_V_34_fu_694_p4 = {{y_cordic_V_22_fu_689_p3[14:7]}};

assign r_V_35_fu_708_p4 = {{x_cordic_V_22_fu_684_p3[14:7]}};

assign r_V_36_fu_772_p4 = {{y_cordic_V_25_fu_767_p3[14:8]}};

assign r_V_37_fu_786_p4 = {{x_cordic_V_25_fu_762_p3[14:8]}};

assign r_V_38_fu_850_p4 = {{y_cordic_V_28_fu_845_p3[14:9]}};

assign r_V_39_fu_864_p4 = {{x_cordic_V_28_fu_840_p3[14:9]}};

assign r_V_40_fu_991_p4 = {{y_cordic_V_31_fu_986_p3[14:10]}};

assign select_ln1697_10_fu_592_p3 = ((tmp_11_fu_584_p3[0:0] == 1'b1) ? 10'd896 : 10'd128);

assign select_ln1697_13_fu_953_p3 = ((tmp_13_reg_1436[0:0] == 1'b1) ? 8'd192 : 8'd64);

assign select_ln1697_16_fu_960_p3 = ((tmp_15_reg_1467[0:0] == 1'b1) ? 14'd16352 : 14'd32);

assign select_ln1697_19_fu_967_p3 = ((tmp_17_reg_1498[0:0] == 1'b1) ? 8'd240 : 8'd16);

assign select_ln1697_22_fu_974_p3 = ((tmp_19_reg_1529[0:0] == 1'b1) ? 8'd248 : 8'd8);

assign select_ln1697_4_fu_946_p3 = ((tmp_7_reg_1324[0:0] == 1'b1) ? 11'd1030 : 11'd0);

assign select_ln1697_7_fu_524_p3 = ((tmp_9_fu_517_p3[0:0] == 1'b1) ? 10'd768 : 10'd256);

assign select_ln1697_fu_939_p3 = ((tmp_5_reg_1291[0:0] == 1'b1) ? 14'd14378 : 14'd0);

assign select_ln36_fu_1033_p3 = ((tmp_21_fu_1025_p3[0:0] == 1'b1) ? 11'd1508 : 11'd1516);

assign select_ln55_fu_1176_p3 = ((tmp_22_fu_1169_p3[0:0] == 1'b1) ? 15'd19900 : 15'd12868);

assign sext_ln1534_10_fu_626_p1 = $signed(r_V_32_fu_616_p4);

assign sext_ln1534_11_fu_640_p1 = $signed(r_V_33_fu_630_p4);

assign sext_ln1534_12_fu_704_p1 = $signed(r_V_34_fu_694_p4);

assign sext_ln1534_13_fu_718_p1 = $signed(r_V_35_fu_708_p4);

assign sext_ln1534_14_fu_782_p1 = $signed(r_V_36_fu_772_p4);

assign sext_ln1534_15_fu_796_p1 = $signed(r_V_37_fu_786_p4);

assign sext_ln1534_16_fu_860_p1 = $signed(r_V_38_fu_850_p4);

assign sext_ln1534_17_fu_874_p1 = $signed(r_V_39_fu_864_p4);

assign sext_ln1534_18_fu_1001_p1 = $signed(r_V_40_fu_991_p4);

assign sext_ln1534_19_fu_1087_p1 = $signed(r_1_fu_1077_p4);

assign sext_ln1534_1_fu_257_p1 = $signed(r_V_23_reg_1251);

assign sext_ln1534_20_fu_1101_p1 = $signed(r_2_fu_1091_p4);

assign sext_ln1534_21_fu_1148_p1 = $signed(r_3_reg_1604);

assign sext_ln1534_22_fu_1151_p1 = $signed(r_V_reg_1609);

assign sext_ln1534_2_fu_330_p1 = $signed(r_V_24_reg_1275);

assign sext_ln1534_3_fu_333_p1 = $signed(r_V_25_reg_1280);

assign sext_ln1534_4_fu_406_p1 = $signed(r_V_26_reg_1308);

assign sext_ln1534_5_fu_409_p1 = $signed(r_V_27_reg_1313);

assign sext_ln1534_6_fu_474_p1 = $signed(r_V_28_reg_1342);

assign sext_ln1534_7_fu_477_p1 = $signed(r_V_29_reg_1347);

assign sext_ln1534_8_fu_547_p1 = $signed(r_V_30_fu_537_p4);

assign sext_ln1534_9_fu_551_p1 = $signed(r_V_31_reg_1374);

assign sext_ln1534_fu_254_p1 = $signed(r_V_22_reg_1246);

assign sext_ln36_1_fu_1059_p1 = $signed(add_ln36_5_reg_1405);

assign sext_ln36_2_fu_1166_p1 = $signed(theta_out_V_3_reg_1619);

assign sext_ln36_fu_1131_p1 = $signed(add_ln36_1_reg_1589);

assign sub_ln1394_fu_1154_p2 = ($signed(add_ln1394_reg_1614) - $signed(sext_ln1534_22_fu_1151_p1));

assign theta = ((tmp_reg_1203[0:0] == 1'b1) ? add_ln55_fu_1184_p2 : sext_ln36_2_fu_1166_p1);

assign theta_out_V_1_fu_925_p3 = ((tmp_2_reg_1228[0:0] == 1'b1) ? 14'd11268 : 14'd1318);

assign theta_out_V_2_fu_932_p3 = ((tmp_3_reg_1256[0:0] == 1'b1) ? theta_out_V_1_fu_925_p3 : theta_out_V_fu_918_p3);

assign theta_out_V_3_fu_1142_p2 = (zext_ln36_fu_1139_p1 + add_ln36_4_fu_1134_p2);

assign theta_out_V_fu_918_p3 = ((tmp_2_reg_1228[0:0] == 1'b1) ? 14'd15066 : 14'd5116);

assign tmp_11_fu_584_p3 = y_cordic_V_16_fu_532_p3[32'd14];

assign tmp_21_fu_1025_p3 = y_cordic_V_31_fu_986_p3[32'd14];

assign tmp_22_fu_1169_p3 = y[32'd14];

assign tmp_9_fu_517_p3 = y_cordic_V_13_reg_1335[32'd14];

assign tmp_fu_148_p3 = x[32'd14];

assign x_cordic_V_10_fu_356_p3 = ((tmp_4_reg_1285[0:0] == 1'b1) ? x_cordic_V_9_fu_346_p2 : x_cordic_V_8_fu_336_p2);

assign x_cordic_V_11_fu_412_p2 = ($signed(x_cordic_V_10_reg_1296) + $signed(sext_ln1534_4_fu_406_p1));

assign x_cordic_V_12_fu_422_p2 = ($signed(x_cordic_V_10_reg_1296) - $signed(sext_ln1534_4_fu_406_p1));

assign x_cordic_V_13_fu_432_p3 = ((tmp_6_reg_1318[0:0] == 1'b1) ? x_cordic_V_12_fu_422_p2 : x_cordic_V_11_fu_412_p2);

assign x_cordic_V_14_fu_480_p2 = ($signed(x_cordic_V_13_reg_1329) + $signed(sext_ln1534_6_fu_474_p1));

assign x_cordic_V_15_fu_490_p2 = ($signed(x_cordic_V_13_reg_1329) - $signed(sext_ln1534_6_fu_474_p1));

assign x_cordic_V_16_fu_500_p3 = ((tmp_8_reg_1352[0:0] == 1'b1) ? x_cordic_V_15_fu_490_p2 : x_cordic_V_14_fu_480_p2);

assign x_cordic_V_17_fu_562_p2 = ($signed(x_cordic_V_16_reg_1368) + $signed(sext_ln1534_8_fu_547_p1));

assign x_cordic_V_18_fu_573_p2 = ($signed(x_cordic_V_16_reg_1368) - $signed(sext_ln1534_8_fu_547_p1));

assign x_cordic_V_19_fu_606_p3 = ((tmp_10_reg_1379[0:0] == 1'b1) ? x_cordic_V_18_reg_1395 : x_cordic_V_17_reg_1385);

assign x_cordic_V_20_fu_652_p2 = ($signed(x_cordic_V_19_fu_606_p3) + $signed(sext_ln1534_10_fu_626_p1));

assign x_cordic_V_21_fu_664_p2 = ($signed(x_cordic_V_19_fu_606_p3) - $signed(sext_ln1534_10_fu_626_p1));

assign x_cordic_V_22_fu_684_p3 = ((tmp_12_reg_1410[0:0] == 1'b1) ? x_cordic_V_21_reg_1426 : x_cordic_V_20_reg_1416);

assign x_cordic_V_23_fu_730_p2 = ($signed(x_cordic_V_22_fu_684_p3) + $signed(sext_ln1534_12_fu_704_p1));

assign x_cordic_V_24_fu_742_p2 = ($signed(x_cordic_V_22_fu_684_p3) - $signed(sext_ln1534_12_fu_704_p1));

assign x_cordic_V_25_fu_762_p3 = ((tmp_14_reg_1441[0:0] == 1'b1) ? x_cordic_V_24_reg_1457 : x_cordic_V_23_reg_1447);

assign x_cordic_V_26_fu_808_p2 = ($signed(x_cordic_V_25_fu_762_p3) + $signed(sext_ln1534_14_fu_782_p1));

assign x_cordic_V_27_fu_820_p2 = ($signed(x_cordic_V_25_fu_762_p3) - $signed(sext_ln1534_14_fu_782_p1));

assign x_cordic_V_28_fu_840_p3 = ((tmp_16_reg_1472[0:0] == 1'b1) ? x_cordic_V_27_reg_1488 : x_cordic_V_26_reg_1478);

assign x_cordic_V_29_fu_886_p2 = ($signed(x_cordic_V_28_fu_840_p3) + $signed(sext_ln1534_16_fu_860_p1));

assign x_cordic_V_30_fu_898_p2 = ($signed(x_cordic_V_28_fu_840_p3) - $signed(sext_ln1534_16_fu_860_p1));

assign x_cordic_V_31_fu_981_p3 = ((tmp_18_reg_1503[0:0] == 1'b1) ? x_cordic_V_30_reg_1519 : x_cordic_V_29_reg_1509);

assign x_cordic_V_32_fu_1013_p2 = ($signed(x_cordic_V_31_fu_981_p3) + $signed(sext_ln1534_18_fu_1001_p1));

assign x_cordic_V_33_fu_1019_p2 = ($signed(x_cordic_V_31_fu_981_p3) - $signed(sext_ln1534_18_fu_1001_p1));

assign x_cordic_V_34_fu_1072_p3 = ((tmp_20_reg_1569[0:0] == 1'b1) ? x_cordic_V_33_reg_1579 : x_cordic_V_32_reg_1574);

assign x_cordic_V_35_fu_168_p3 = ((tmp_fu_148_p3[0:0] == 1'b1) ? x_cordic_V_fu_156_p2 : x);

assign x_cordic_V_36_fu_200_p2 = (y_cordic_V_32_reg_1215 + x_cordic_V_35_reg_1208);

assign x_cordic_V_3_fu_208_p2 = (x_cordic_V_35_reg_1208 - y_cordic_V_32_reg_1215);

assign x_cordic_V_4_fu_212_p3 = ((tmp_1_reg_1222[0:0] == 1'b1) ? x_cordic_V_3_fu_208_p2 : x_cordic_V_36_fu_200_p2);

assign x_cordic_V_5_fu_260_p2 = ($signed(x_cordic_V_4_reg_1234) + $signed(sext_ln1534_fu_254_p1));

assign x_cordic_V_6_fu_270_p2 = ($signed(x_cordic_V_4_reg_1234) - $signed(sext_ln1534_fu_254_p1));

assign x_cordic_V_7_fu_280_p3 = ((tmp_3_reg_1256[0:0] == 1'b1) ? x_cordic_V_6_fu_270_p2 : x_cordic_V_5_fu_260_p2);

assign x_cordic_V_8_fu_336_p2 = ($signed(x_cordic_V_7_reg_1263) + $signed(sext_ln1534_2_fu_330_p1));

assign x_cordic_V_9_fu_346_p2 = ($signed(x_cordic_V_7_reg_1263) - $signed(sext_ln1534_2_fu_330_p1));

assign x_cordic_V_fu_156_p2 = (15'd0 - x);

assign y_cordic_V_10_fu_363_p3 = ((tmp_4_reg_1285[0:0] == 1'b1) ? y_cordic_V_9_fu_351_p2 : y_cordic_V_8_fu_341_p2);

assign y_cordic_V_11_fu_417_p2 = ($signed(y_cordic_V_10_reg_1302) - $signed(sext_ln1534_5_fu_409_p1));

assign y_cordic_V_12_fu_427_p2 = ($signed(y_cordic_V_10_reg_1302) + $signed(sext_ln1534_5_fu_409_p1));

assign y_cordic_V_13_fu_439_p3 = ((tmp_6_reg_1318[0:0] == 1'b1) ? y_cordic_V_12_fu_427_p2 : y_cordic_V_11_fu_417_p2);

assign y_cordic_V_14_fu_485_p2 = ($signed(y_cordic_V_13_reg_1335) - $signed(sext_ln1534_7_fu_477_p1));

assign y_cordic_V_15_fu_495_p2 = ($signed(y_cordic_V_13_reg_1335) + $signed(sext_ln1534_7_fu_477_p1));

assign y_cordic_V_16_fu_532_p3 = ((tmp_8_reg_1352[0:0] == 1'b1) ? y_cordic_V_15_reg_1363 : y_cordic_V_14_reg_1358);

assign y_cordic_V_17_fu_567_p2 = ($signed(y_cordic_V_16_fu_532_p3) - $signed(sext_ln1534_9_fu_551_p1));

assign y_cordic_V_18_fu_578_p2 = ($signed(y_cordic_V_16_fu_532_p3) + $signed(sext_ln1534_9_fu_551_p1));

assign y_cordic_V_19_fu_611_p3 = ((tmp_10_reg_1379[0:0] == 1'b1) ? y_cordic_V_18_reg_1400 : y_cordic_V_17_reg_1390);

assign y_cordic_V_20_fu_658_p2 = ($signed(y_cordic_V_19_fu_611_p3) - $signed(sext_ln1534_11_fu_640_p1));

assign y_cordic_V_21_fu_670_p2 = ($signed(y_cordic_V_19_fu_611_p3) + $signed(sext_ln1534_11_fu_640_p1));

assign y_cordic_V_22_fu_689_p3 = ((tmp_12_reg_1410[0:0] == 1'b1) ? y_cordic_V_21_reg_1431 : y_cordic_V_20_reg_1421);

assign y_cordic_V_23_fu_736_p2 = ($signed(y_cordic_V_22_fu_689_p3) - $signed(sext_ln1534_13_fu_718_p1));

assign y_cordic_V_24_fu_748_p2 = ($signed(y_cordic_V_22_fu_689_p3) + $signed(sext_ln1534_13_fu_718_p1));

assign y_cordic_V_25_fu_767_p3 = ((tmp_14_reg_1441[0:0] == 1'b1) ? y_cordic_V_24_reg_1462 : y_cordic_V_23_reg_1452);

assign y_cordic_V_26_fu_814_p2 = ($signed(y_cordic_V_25_fu_767_p3) - $signed(sext_ln1534_15_fu_796_p1));

assign y_cordic_V_27_fu_826_p2 = ($signed(y_cordic_V_25_fu_767_p3) + $signed(sext_ln1534_15_fu_796_p1));

assign y_cordic_V_28_fu_845_p3 = ((tmp_16_reg_1472[0:0] == 1'b1) ? y_cordic_V_27_reg_1493 : y_cordic_V_26_reg_1483);

assign y_cordic_V_29_fu_892_p2 = ($signed(y_cordic_V_28_fu_845_p3) - $signed(sext_ln1534_17_fu_874_p1));

assign y_cordic_V_2_fu_204_p2 = (y_cordic_V_32_reg_1215 - x_cordic_V_35_reg_1208);

assign y_cordic_V_30_fu_904_p2 = ($signed(y_cordic_V_28_fu_845_p3) + $signed(sext_ln1534_17_fu_874_p1));

assign y_cordic_V_31_fu_986_p3 = ((tmp_18_reg_1503[0:0] == 1'b1) ? y_cordic_V_30_reg_1524 : y_cordic_V_29_reg_1514);

assign y_cordic_V_32_fu_176_p3 = ((tmp_fu_148_p3[0:0] == 1'b1) ? y_cordic_V_fu_162_p2 : y);

assign y_cordic_V_4_fu_219_p3 = ((tmp_1_reg_1222[0:0] == 1'b1) ? x_cordic_V_36_fu_200_p2 : y_cordic_V_2_fu_204_p2);

assign y_cordic_V_5_fu_265_p2 = ($signed(y_cordic_V_4_reg_1240) - $signed(sext_ln1534_1_fu_257_p1));

assign y_cordic_V_6_fu_275_p2 = ($signed(y_cordic_V_4_reg_1240) + $signed(sext_ln1534_1_fu_257_p1));

assign y_cordic_V_7_fu_287_p3 = ((tmp_3_reg_1256[0:0] == 1'b1) ? y_cordic_V_6_fu_275_p2 : y_cordic_V_5_fu_265_p2);

assign y_cordic_V_8_fu_341_p2 = ($signed(y_cordic_V_7_reg_1269) - $signed(sext_ln1534_3_fu_333_p1));

assign y_cordic_V_9_fu_351_p2 = ($signed(y_cordic_V_7_reg_1269) + $signed(sext_ln1534_3_fu_333_p1));

assign y_cordic_V_fu_162_p2 = (15'd0 - y);

assign zext_ln36_fu_1139_p1 = add_ln36_7_reg_1599;

always @ (posedge ap_clk) begin
    add_ln36_5_reg_1405[7:0] <= 8'b10000000;
    theta_out_V_2_reg_1534[0] <= 1'b0;
    select_ln1697_reg_1539[0] <= 1'b0;
    select_ln1697_reg_1539[2:2] <= 1'b0;
    select_ln1697_reg_1539[4:4] <= 1'b0;
    select_ln1697_reg_1539[10:6] <= 5'b00000;
    select_ln1697_4_reg_1544[0] <= 1'b0;
    select_ln1697_4_reg_1544[9:3] <= 7'b0000000;
    select_ln1697_13_reg_1549[6:0] <= 7'b1000000;
    select_ln1697_16_reg_1554[5:0] <= 6'b100000;
    select_ln1697_19_reg_1559[4:0] <= 5'b10000;
    select_ln1697_22_reg_1564[3:0] <= 4'b1000;
    select_ln36_reg_1584[2:0] <= 3'b100;
    select_ln36_reg_1584[10:4] <= 7'b1011110;
    add_ln36_1_reg_1589[3:0] <= 4'b1000;
    add_ln36_3_reg_1594[0] <= 1'b0;
    add_ln36_7_reg_1599[0] <= 1'b0;
    theta_out_V_3_reg_1619[0] <= 1'b0;
end

endmodule //cordiccart2pol
