#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("pk_address0", 11, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("pk_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("pk_we0", 1, hls_out, 0, "ap_memory", "mem_we", 1),
	Port_Property("pk_d0", 8, hls_out, 0, "ap_memory", "mem_din", 1),
	Port_Property("pk_q0", 8, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("pk_address1", 11, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("pk_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("pk_we1", 1, hls_out, 0, "ap_memory", "MemPortWE2", 1),
	Port_Property("pk_d1", 8, hls_out, 0, "ap_memory", "MemPortDIN2", 1),
	Port_Property("pk_q1", 8, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("sk_address0", 12, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("sk_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("sk_we0", 1, hls_out, 1, "ap_memory", "mem_we", 1),
	Port_Property("sk_d0", 8, hls_out, 1, "ap_memory", "mem_din", 1),
	Port_Property("sk_q0", 8, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("sk_address1", 12, hls_out, 1, "ap_memory", "MemPortADDR2", 1),
	Port_Property("sk_ce1", 1, hls_out, 1, "ap_memory", "MemPortCE2", 1),
	Port_Property("sk_we1", 1, hls_out, 1, "ap_memory", "MemPortWE2", 1),
	Port_Property("sk_d1", 8, hls_out, 1, "ap_memory", "MemPortDIN2", 1),
	Port_Property("sk_q1", 8, hls_in, 1, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("seedbuf_address0", 7, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("seedbuf_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("seedbuf_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("seedbuf_d0", 8, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("seedbuf_q0", 8, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("seedbuf_address1", 7, hls_out, 2, "ap_memory", "MemPortADDR2", 1),
	Port_Property("seedbuf_ce1", 1, hls_out, 2, "ap_memory", "MemPortCE2", 1),
	Port_Property("seedbuf_we1", 1, hls_out, 2, "ap_memory", "MemPortWE2", 1),
	Port_Property("seedbuf_d1", 8, hls_out, 2, "ap_memory", "MemPortDIN2", 1),
	Port_Property("seedbuf_q1", 8, hls_in, 2, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("ap_return", 32, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "dpu_keygen";
