// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Loop_memset_AB_proc8.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Loop_memset_AB_proc8::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Loop_memset_AB_proc8::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> Loop_memset_AB_proc8::ap_ST_fsm_state1 = "1";
const sc_lv<9> Loop_memset_AB_proc8::ap_ST_fsm_state2 = "10";
const sc_lv<9> Loop_memset_AB_proc8::ap_ST_fsm_state3 = "100";
const sc_lv<9> Loop_memset_AB_proc8::ap_ST_fsm_pp0_stage0 = "1000";
const sc_lv<9> Loop_memset_AB_proc8::ap_ST_fsm_pp0_stage1 = "10000";
const sc_lv<9> Loop_memset_AB_proc8::ap_ST_fsm_state7 = "100000";
const sc_lv<9> Loop_memset_AB_proc8::ap_ST_fsm_state8 = "1000000";
const sc_lv<9> Loop_memset_AB_proc8::ap_ST_fsm_pp1_stage0 = "10000000";
const sc_lv<9> Loop_memset_AB_proc8::ap_ST_fsm_state13 = "100000000";
const sc_lv<32> Loop_memset_AB_proc8::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Loop_memset_AB_proc8::ap_const_boolean_1 = true;
const sc_lv<32> Loop_memset_AB_proc8::ap_const_lv32_4 = "100";
const bool Loop_memset_AB_proc8::ap_const_boolean_0 = false;
const sc_lv<1> Loop_memset_AB_proc8::ap_const_lv1_0 = "0";
const sc_lv<32> Loop_memset_AB_proc8::ap_const_lv32_6 = "110";
const sc_lv<32> Loop_memset_AB_proc8::ap_const_lv32_1 = "1";
const sc_lv<32> Loop_memset_AB_proc8::ap_const_lv32_2 = "10";
const sc_lv<1> Loop_memset_AB_proc8::ap_const_lv1_1 = "1";
const sc_lv<32> Loop_memset_AB_proc8::ap_const_lv32_3 = "11";
const sc_lv<32> Loop_memset_AB_proc8::ap_const_lv32_7 = "111";
const sc_lv<2> Loop_memset_AB_proc8::ap_const_lv2_0 = "00";
const sc_lv<4> Loop_memset_AB_proc8::ap_const_lv4_0 = "0000";
const sc_lv<32> Loop_memset_AB_proc8::ap_const_lv32_5 = "101";
const sc_lv<32> Loop_memset_AB_proc8::ap_const_lv32_8 = "1000";
const sc_lv<5> Loop_memset_AB_proc8::ap_const_lv5_0 = "00000";
const sc_lv<3> Loop_memset_AB_proc8::ap_const_lv3_0 = "000";
const sc_lv<2> Loop_memset_AB_proc8::ap_const_lv2_1 = "1";
const sc_lv<2> Loop_memset_AB_proc8::ap_const_lv2_3 = "11";
const sc_lv<4> Loop_memset_AB_proc8::ap_const_lv4_8 = "1000";
const sc_lv<4> Loop_memset_AB_proc8::ap_const_lv4_1 = "1";
const sc_lv<60> Loop_memset_AB_proc8::ap_const_lv60_1 = "1";
const sc_lv<5> Loop_memset_AB_proc8::ap_const_lv5_10 = "10000";
const sc_lv<5> Loop_memset_AB_proc8::ap_const_lv5_1 = "1";
const sc_lv<3> Loop_memset_AB_proc8::ap_const_lv3_1 = "1";
const sc_lv<3> Loop_memset_AB_proc8::ap_const_lv3_4 = "100";

Loop_memset_AB_proc8::Loop_memset_AB_proc8(sc_module_name name) : sc_module(name), mVcdFile(0) {
    A_U = new Loop_memset_AB_prbkb("A_U");
    A_U->clk(ap_clk);
    A_U->reset(ap_rst);
    A_U->address0(A_address0);
    A_U->ce0(A_ce0);
    A_U->we0(A_we0);
    A_U->d0(A_d0);
    A_U->q0(A_q0);
    A_U->address1(A_address1);
    A_U->ce1(A_ce1);
    A_U->we1(A_we1);
    A_U->d1(A_d1);
    blockmatmul_mux_4cud_U1 = new blockmatmul_mux_4cud<1,1,32,32,32,32,2,32>("blockmatmul_mux_4cud_U1");
    blockmatmul_mux_4cud_U1->din0(tmp_a_1_05_reg_600);
    blockmatmul_mux_4cud_U1->din1(tmp_a_1_16_reg_605);
    blockmatmul_mux_4cud_U1->din2(tmp_a_1_27_reg_610);
    blockmatmul_mux_4cud_U1->din3(tmp_a_1_38_reg_615);
    blockmatmul_mux_4cud_U1->din4(trunc_ln28_reg_650);
    blockmatmul_mux_4cud_U1->dout(tmp_2_fu_521_p6);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_AB_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( AB_addr_2_reg_660 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( zext_ln7_fu_303_p1 );

    SC_METHOD(thread_AB_address1);
    sensitive << ( AB_addr_2_reg_660_pp1_iter2_reg );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_AB_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter2 );

    SC_METHOD(thread_AB_ce1);
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter3 );

    SC_METHOD(thread_AB_d0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_AB_d1);
    sensitive << ( AB_q0 );
    sensitive << ( mul_ln28_reg_676 );
    sensitive << ( ap_enable_reg_pp1_iter3 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_AB_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_AB_we1);
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( icmp_ln25_reg_625_pp1_iter2_reg );
    sensitive << ( ap_enable_reg_pp1_iter3 );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( zext_ln17_fu_359_p1 );
    sensitive << ( tmp_6_fu_375_p3 );
    sensitive << ( zext_ln28_1_fu_481_p1 );

    SC_METHOD(thread_A_address1);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln17_1_fu_370_p1 );
    sensitive << ( zext_ln17_2_fu_387_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_A_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_A_d0);
    sensitive << ( Arows_V_a_0_dout );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_a_23_reg_576 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_A_d1);
    sensitive << ( Arows_V_a_1_dout );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_a_34_reg_581 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_A_we0);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln13_reg_567 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_A_we1);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln13_reg_567 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_Arows_V_a_0_blk_n);
    sensitive << ( Arows_V_a_0_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( icmp_ln13_reg_567 );

    SC_METHOD(thread_Arows_V_a_0_read);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln13_reg_567 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_Arows_V_a_1_blk_n);
    sensitive << ( Arows_V_a_1_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( icmp_ln13_reg_567 );

    SC_METHOD(thread_Arows_V_a_1_read);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln13_reg_567 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_Arows_V_a_2_blk_n);
    sensitive << ( Arows_V_a_2_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( icmp_ln13_reg_567 );

    SC_METHOD(thread_Arows_V_a_2_read);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln13_reg_567 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_Arows_V_a_3_blk_n);
    sensitive << ( Arows_V_a_3_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( icmp_ln13_reg_567 );

    SC_METHOD(thread_Arows_V_a_3_read);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln13_reg_567 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_Bcols_V_a_0_blk_n);
    sensitive << ( Bcols_V_a_0_empty_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln22_fu_392_p2 );

    SC_METHOD(thread_Bcols_V_a_0_read);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln22_fu_392_p2 );
    sensitive << ( io_acc_block_signal_op82 );

    SC_METHOD(thread_Bcols_V_a_1_blk_n);
    sensitive << ( Bcols_V_a_1_empty_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln22_fu_392_p2 );

    SC_METHOD(thread_Bcols_V_a_1_read);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln22_fu_392_p2 );
    sensitive << ( io_acc_block_signal_op82 );

    SC_METHOD(thread_Bcols_V_a_2_blk_n);
    sensitive << ( Bcols_V_a_2_empty_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln22_fu_392_p2 );

    SC_METHOD(thread_Bcols_V_a_2_read);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln22_fu_392_p2 );
    sensitive << ( io_acc_block_signal_op82 );

    SC_METHOD(thread_Bcols_V_a_3_blk_n);
    sensitive << ( Bcols_V_a_3_empty_n );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln22_fu_392_p2 );

    SC_METHOD(thread_Bcols_V_a_3_read);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln22_fu_392_p2 );
    sensitive << ( io_acc_block_signal_op82 );

    SC_METHOD(thread_add_ln25_fu_430_p2);
    sensitive << ( indvar_flatten_reg_256 );

    SC_METHOD(thread_add_ln28_1_fu_476_p2);
    sensitive << ( zext_ln25_reg_620 );
    sensitive << ( zext_ln28_fu_472_p1 );

    SC_METHOD(thread_add_ln28_2_fu_510_p2);
    sensitive << ( zext_ln26_fu_503_p1 );
    sensitive << ( zext_ln28_2_fu_507_p1 );

    SC_METHOD(thread_add_ln7_1_fu_308_p2);
    sensitive << ( phi_ln7_1_reg_222 );

    SC_METHOD(thread_add_ln7_fu_289_p2);
    sensitive << ( phi_ln7_reg_210 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln13_reg_567 );
    sensitive << ( io_acc_block_signal_op49 );

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln13_reg_567 );
    sensitive << ( io_acc_block_signal_op49 );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp1_stage0_iter1);

    SC_METHOD(thread_ap_block_state11_pp1_stage0_iter2);

    SC_METHOD(thread_ap_block_state12_pp1_stage0_iter3);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage1_iter0);
    sensitive << ( icmp_ln13_reg_567 );
    sensitive << ( io_acc_block_signal_op49 );

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state8);
    sensitive << ( icmp_ln22_fu_392_p2 );
    sensitive << ( io_acc_block_signal_op82 );

    SC_METHOD(thread_ap_block_state9_pp1_stage0_iter0);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state4);
    sensitive << ( icmp_ln13_fu_329_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state9);
    sensitive << ( icmp_ln25_fu_424_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln22_fu_392_p2 );
    sensitive << ( io_acc_block_signal_op82 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_enable_reg_pp1_iter3 );

    SC_METHOD(thread_ap_phi_mux_i1_0_phi_fu_271_p4);
    sensitive << ( i1_0_reg_267 );
    sensitive << ( icmp_ln25_reg_625 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( select_ln28_1_reg_639 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_ap_phi_mux_i_0_phi_fu_237_p4);
    sensitive << ( icmp_ln13_reg_567 );
    sensitive << ( i_0_reg_233 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_reg_571 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln22_fu_392_p2 );
    sensitive << ( io_acc_block_signal_op82 );

    SC_METHOD(thread_i_1_fu_436_p2);
    sensitive << ( ap_phi_mux_i1_0_phi_fu_271_p4 );

    SC_METHOD(thread_i_fu_335_p2);
    sensitive << ( ap_phi_mux_i_0_phi_fu_237_p4 );

    SC_METHOD(thread_icmp_ln13_fu_329_p2);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_237_p4 );

    SC_METHOD(thread_icmp_ln22_fu_392_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln22_fu_392_p2 );
    sensitive << ( io_acc_block_signal_op82 );
    sensitive << ( k_0_reg_245 );

    SC_METHOD(thread_icmp_ln25_fu_424_p2);
    sensitive << ( indvar_flatten_reg_256 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln26_fu_442_p2);
    sensitive << ( j2_0_reg_278 );
    sensitive << ( icmp_ln25_fu_424_p2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln7_1_fu_320_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln7_fu_314_p2 );
    sensitive << ( phi_ln7_reg_210 );

    SC_METHOD(thread_icmp_ln7_fu_314_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( phi_ln7_1_reg_222 );

    SC_METHOD(thread_io_acc_block_signal_op49);
    sensitive << ( Arows_V_a_0_empty_n );
    sensitive << ( Arows_V_a_1_empty_n );
    sensitive << ( Arows_V_a_2_empty_n );
    sensitive << ( Arows_V_a_3_empty_n );

    SC_METHOD(thread_io_acc_block_signal_op82);
    sensitive << ( Bcols_V_a_0_empty_n );
    sensitive << ( Bcols_V_a_1_empty_n );
    sensitive << ( Bcols_V_a_2_empty_n );
    sensitive << ( Bcols_V_a_3_empty_n );

    SC_METHOD(thread_j_fu_490_p2);
    sensitive << ( select_ln28_fu_448_p3 );

    SC_METHOD(thread_k_fu_398_p2);
    sensitive << ( k_0_reg_245 );

    SC_METHOD(thread_mul_ln28_fu_530_p2);
    sensitive << ( A_load_reg_666 );
    sensitive << ( tmp_2_reg_671 );

    SC_METHOD(thread_select_ln28_1_fu_456_p3);
    sensitive << ( ap_phi_mux_i1_0_phi_fu_271_p4 );
    sensitive << ( icmp_ln26_fu_442_p2 );
    sensitive << ( i_1_fu_436_p2 );

    SC_METHOD(thread_select_ln28_fu_448_p3);
    sensitive << ( j2_0_reg_278 );
    sensitive << ( icmp_ln26_fu_442_p2 );

    SC_METHOD(thread_sext_ln17_fu_384_p1);
    sensitive << ( xor_ln17_reg_586 );

    SC_METHOD(thread_tmp_5_fu_295_p3);
    sensitive << ( phi_ln7_reg_210 );
    sensitive << ( phi_ln7_1_reg_222 );

    SC_METHOD(thread_tmp_6_fu_375_p3);
    sensitive << ( i_0_reg_233 );

    SC_METHOD(thread_tmp_7_fu_464_p3);
    sensitive << ( select_ln28_1_fu_456_p3 );

    SC_METHOD(thread_tmp_8_fu_496_p3);
    sensitive << ( select_ln28_1_reg_639 );

    SC_METHOD(thread_trunc_ln12_fu_326_p1);
    sensitive << ( it );

    SC_METHOD(thread_trunc_ln28_fu_486_p1);
    sensitive << ( select_ln28_fu_448_p3 );

    SC_METHOD(thread_xor_ln17_fu_364_p2);
    sensitive << ( i_0_reg_233 );

    SC_METHOD(thread_zext_ln17_1_fu_370_p1);
    sensitive << ( xor_ln17_fu_364_p2 );

    SC_METHOD(thread_zext_ln17_2_fu_387_p1);
    sensitive << ( sext_ln17_fu_384_p1 );

    SC_METHOD(thread_zext_ln17_fu_359_p1);
    sensitive << ( i_0_reg_233 );

    SC_METHOD(thread_zext_ln25_fu_420_p1);
    sensitive << ( k_0_reg_245 );

    SC_METHOD(thread_zext_ln26_fu_503_p1);
    sensitive << ( tmp_8_fu_496_p3 );

    SC_METHOD(thread_zext_ln28_1_fu_481_p1);
    sensitive << ( add_ln28_1_fu_476_p2 );

    SC_METHOD(thread_zext_ln28_2_fu_507_p1);
    sensitive << ( select_ln28_reg_634 );

    SC_METHOD(thread_zext_ln28_3_fu_516_p1);
    sensitive << ( add_ln28_2_fu_510_p2 );

    SC_METHOD(thread_zext_ln28_fu_472_p1);
    sensitive << ( tmp_7_fu_464_p3 );

    SC_METHOD(thread_zext_ln7_fu_303_p1);
    sensitive << ( tmp_5_fu_295_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln22_fu_392_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln7_fu_314_p2 );
    sensitive << ( icmp_ln7_1_fu_320_p2 );
    sensitive << ( trunc_ln12_fu_326_p1 );
    sensitive << ( icmp_ln13_fu_329_p2 );
    sensitive << ( io_acc_block_signal_op82 );
    sensitive << ( icmp_ln25_fu_424_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_enable_reg_pp1_iter3 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Loop_memset_AB_proc8_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, AB_address0, "(port)AB_address0");
    sc_trace(mVcdFile, AB_ce0, "(port)AB_ce0");
    sc_trace(mVcdFile, AB_we0, "(port)AB_we0");
    sc_trace(mVcdFile, AB_d0, "(port)AB_d0");
    sc_trace(mVcdFile, AB_q0, "(port)AB_q0");
    sc_trace(mVcdFile, AB_address1, "(port)AB_address1");
    sc_trace(mVcdFile, AB_ce1, "(port)AB_ce1");
    sc_trace(mVcdFile, AB_we1, "(port)AB_we1");
    sc_trace(mVcdFile, AB_d1, "(port)AB_d1");
    sc_trace(mVcdFile, it, "(port)it");
    sc_trace(mVcdFile, Arows_V_a_0_dout, "(port)Arows_V_a_0_dout");
    sc_trace(mVcdFile, Arows_V_a_0_empty_n, "(port)Arows_V_a_0_empty_n");
    sc_trace(mVcdFile, Arows_V_a_0_read, "(port)Arows_V_a_0_read");
    sc_trace(mVcdFile, Arows_V_a_1_dout, "(port)Arows_V_a_1_dout");
    sc_trace(mVcdFile, Arows_V_a_1_empty_n, "(port)Arows_V_a_1_empty_n");
    sc_trace(mVcdFile, Arows_V_a_1_read, "(port)Arows_V_a_1_read");
    sc_trace(mVcdFile, Arows_V_a_2_dout, "(port)Arows_V_a_2_dout");
    sc_trace(mVcdFile, Arows_V_a_2_empty_n, "(port)Arows_V_a_2_empty_n");
    sc_trace(mVcdFile, Arows_V_a_2_read, "(port)Arows_V_a_2_read");
    sc_trace(mVcdFile, Arows_V_a_3_dout, "(port)Arows_V_a_3_dout");
    sc_trace(mVcdFile, Arows_V_a_3_empty_n, "(port)Arows_V_a_3_empty_n");
    sc_trace(mVcdFile, Arows_V_a_3_read, "(port)Arows_V_a_3_read");
    sc_trace(mVcdFile, Bcols_V_a_0_dout, "(port)Bcols_V_a_0_dout");
    sc_trace(mVcdFile, Bcols_V_a_0_empty_n, "(port)Bcols_V_a_0_empty_n");
    sc_trace(mVcdFile, Bcols_V_a_0_read, "(port)Bcols_V_a_0_read");
    sc_trace(mVcdFile, Bcols_V_a_1_dout, "(port)Bcols_V_a_1_dout");
    sc_trace(mVcdFile, Bcols_V_a_1_empty_n, "(port)Bcols_V_a_1_empty_n");
    sc_trace(mVcdFile, Bcols_V_a_1_read, "(port)Bcols_V_a_1_read");
    sc_trace(mVcdFile, Bcols_V_a_2_dout, "(port)Bcols_V_a_2_dout");
    sc_trace(mVcdFile, Bcols_V_a_2_empty_n, "(port)Bcols_V_a_2_empty_n");
    sc_trace(mVcdFile, Bcols_V_a_2_read, "(port)Bcols_V_a_2_read");
    sc_trace(mVcdFile, Bcols_V_a_3_dout, "(port)Bcols_V_a_3_dout");
    sc_trace(mVcdFile, Bcols_V_a_3_empty_n, "(port)Bcols_V_a_3_empty_n");
    sc_trace(mVcdFile, Bcols_V_a_3_read, "(port)Bcols_V_a_3_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, A_address0, "A_address0");
    sc_trace(mVcdFile, A_ce0, "A_ce0");
    sc_trace(mVcdFile, A_we0, "A_we0");
    sc_trace(mVcdFile, A_d0, "A_d0");
    sc_trace(mVcdFile, A_q0, "A_q0");
    sc_trace(mVcdFile, A_address1, "A_address1");
    sc_trace(mVcdFile, A_ce1, "A_ce1");
    sc_trace(mVcdFile, A_we1, "A_we1");
    sc_trace(mVcdFile, A_d1, "A_d1");
    sc_trace(mVcdFile, Arows_V_a_0_blk_n, "Arows_V_a_0_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, icmp_ln13_reg_567, "icmp_ln13_reg_567");
    sc_trace(mVcdFile, Arows_V_a_1_blk_n, "Arows_V_a_1_blk_n");
    sc_trace(mVcdFile, Arows_V_a_2_blk_n, "Arows_V_a_2_blk_n");
    sc_trace(mVcdFile, Arows_V_a_3_blk_n, "Arows_V_a_3_blk_n");
    sc_trace(mVcdFile, Bcols_V_a_0_blk_n, "Bcols_V_a_0_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln22_fu_392_p2, "icmp_ln22_fu_392_p2");
    sc_trace(mVcdFile, Bcols_V_a_1_blk_n, "Bcols_V_a_1_blk_n");
    sc_trace(mVcdFile, Bcols_V_a_2_blk_n, "Bcols_V_a_2_blk_n");
    sc_trace(mVcdFile, Bcols_V_a_3_blk_n, "Bcols_V_a_3_blk_n");
    sc_trace(mVcdFile, i_0_reg_233, "i_0_reg_233");
    sc_trace(mVcdFile, indvar_flatten_reg_256, "indvar_flatten_reg_256");
    sc_trace(mVcdFile, i1_0_reg_267, "i1_0_reg_267");
    sc_trace(mVcdFile, j2_0_reg_278, "j2_0_reg_278");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, add_ln7_fu_289_p2, "add_ln7_fu_289_p2");
    sc_trace(mVcdFile, add_ln7_reg_545, "add_ln7_reg_545");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln7_1_fu_308_p2, "add_ln7_1_fu_308_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln7_fu_314_p2, "icmp_ln7_fu_314_p2");
    sc_trace(mVcdFile, icmp_ln7_1_fu_320_p2, "icmp_ln7_1_fu_320_p2");
    sc_trace(mVcdFile, trunc_ln12_fu_326_p1, "trunc_ln12_fu_326_p1");
    sc_trace(mVcdFile, icmp_ln13_fu_329_p2, "icmp_ln13_fu_329_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter0, "ap_block_state4_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter1, "ap_block_state6_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_335_p2, "i_fu_335_p2");
    sc_trace(mVcdFile, i_reg_571, "i_reg_571");
    sc_trace(mVcdFile, tmp_a_23_reg_576, "tmp_a_23_reg_576");
    sc_trace(mVcdFile, io_acc_block_signal_op49, "io_acc_block_signal_op49");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage1_iter0, "ap_block_state5_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, tmp_a_34_reg_581, "tmp_a_34_reg_581");
    sc_trace(mVcdFile, xor_ln17_fu_364_p2, "xor_ln17_fu_364_p2");
    sc_trace(mVcdFile, xor_ln17_reg_586, "xor_ln17_reg_586");
    sc_trace(mVcdFile, io_acc_block_signal_op82, "io_acc_block_signal_op82");
    sc_trace(mVcdFile, ap_block_state8, "ap_block_state8");
    sc_trace(mVcdFile, k_fu_398_p2, "k_fu_398_p2");
    sc_trace(mVcdFile, k_reg_595, "k_reg_595");
    sc_trace(mVcdFile, tmp_a_1_05_reg_600, "tmp_a_1_05_reg_600");
    sc_trace(mVcdFile, tmp_a_1_16_reg_605, "tmp_a_1_16_reg_605");
    sc_trace(mVcdFile, tmp_a_1_27_reg_610, "tmp_a_1_27_reg_610");
    sc_trace(mVcdFile, tmp_a_1_38_reg_615, "tmp_a_1_38_reg_615");
    sc_trace(mVcdFile, zext_ln25_fu_420_p1, "zext_ln25_fu_420_p1");
    sc_trace(mVcdFile, zext_ln25_reg_620, "zext_ln25_reg_620");
    sc_trace(mVcdFile, icmp_ln25_fu_424_p2, "icmp_ln25_fu_424_p2");
    sc_trace(mVcdFile, icmp_ln25_reg_625, "icmp_ln25_reg_625");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_block_state9_pp1_stage0_iter0, "ap_block_state9_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state10_pp1_stage0_iter1, "ap_block_state10_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state11_pp1_stage0_iter2, "ap_block_state11_pp1_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state12_pp1_stage0_iter3, "ap_block_state12_pp1_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, icmp_ln25_reg_625_pp1_iter1_reg, "icmp_ln25_reg_625_pp1_iter1_reg");
    sc_trace(mVcdFile, icmp_ln25_reg_625_pp1_iter2_reg, "icmp_ln25_reg_625_pp1_iter2_reg");
    sc_trace(mVcdFile, add_ln25_fu_430_p2, "add_ln25_fu_430_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, select_ln28_fu_448_p3, "select_ln28_fu_448_p3");
    sc_trace(mVcdFile, select_ln28_reg_634, "select_ln28_reg_634");
    sc_trace(mVcdFile, select_ln28_1_fu_456_p3, "select_ln28_1_fu_456_p3");
    sc_trace(mVcdFile, select_ln28_1_reg_639, "select_ln28_1_reg_639");
    sc_trace(mVcdFile, trunc_ln28_fu_486_p1, "trunc_ln28_fu_486_p1");
    sc_trace(mVcdFile, trunc_ln28_reg_650, "trunc_ln28_reg_650");
    sc_trace(mVcdFile, j_fu_490_p2, "j_fu_490_p2");
    sc_trace(mVcdFile, AB_addr_2_reg_660, "AB_addr_2_reg_660");
    sc_trace(mVcdFile, AB_addr_2_reg_660_pp1_iter2_reg, "AB_addr_2_reg_660_pp1_iter2_reg");
    sc_trace(mVcdFile, A_load_reg_666, "A_load_reg_666");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, tmp_2_fu_521_p6, "tmp_2_fu_521_p6");
    sc_trace(mVcdFile, tmp_2_reg_671, "tmp_2_reg_671");
    sc_trace(mVcdFile, mul_ln28_fu_530_p2, "mul_ln28_fu_530_p2");
    sc_trace(mVcdFile, mul_ln28_reg_676, "mul_ln28_reg_676");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state4, "ap_condition_pp0_exit_iter0_state4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state9, "ap_condition_pp1_exit_iter0_state9");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter2, "ap_enable_reg_pp1_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter3, "ap_enable_reg_pp1_iter3");
    sc_trace(mVcdFile, phi_ln7_reg_210, "phi_ln7_reg_210");
    sc_trace(mVcdFile, phi_ln7_1_reg_222, "phi_ln7_1_reg_222");
    sc_trace(mVcdFile, ap_phi_mux_i_0_phi_fu_237_p4, "ap_phi_mux_i_0_phi_fu_237_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, k_0_reg_245, "k_0_reg_245");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_phi_mux_i1_0_phi_fu_271_p4, "ap_phi_mux_i1_0_phi_fu_271_p4");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, zext_ln7_fu_303_p1, "zext_ln7_fu_303_p1");
    sc_trace(mVcdFile, zext_ln17_fu_359_p1, "zext_ln17_fu_359_p1");
    sc_trace(mVcdFile, zext_ln17_1_fu_370_p1, "zext_ln17_1_fu_370_p1");
    sc_trace(mVcdFile, tmp_6_fu_375_p3, "tmp_6_fu_375_p3");
    sc_trace(mVcdFile, zext_ln17_2_fu_387_p1, "zext_ln17_2_fu_387_p1");
    sc_trace(mVcdFile, zext_ln28_1_fu_481_p1, "zext_ln28_1_fu_481_p1");
    sc_trace(mVcdFile, zext_ln28_3_fu_516_p1, "zext_ln28_3_fu_516_p1");
    sc_trace(mVcdFile, tmp_5_fu_295_p3, "tmp_5_fu_295_p3");
    sc_trace(mVcdFile, sext_ln17_fu_384_p1, "sext_ln17_fu_384_p1");
    sc_trace(mVcdFile, icmp_ln26_fu_442_p2, "icmp_ln26_fu_442_p2");
    sc_trace(mVcdFile, i_1_fu_436_p2, "i_1_fu_436_p2");
    sc_trace(mVcdFile, tmp_7_fu_464_p3, "tmp_7_fu_464_p3");
    sc_trace(mVcdFile, zext_ln28_fu_472_p1, "zext_ln28_fu_472_p1");
    sc_trace(mVcdFile, add_ln28_1_fu_476_p2, "add_ln28_1_fu_476_p2");
    sc_trace(mVcdFile, tmp_8_fu_496_p3, "tmp_8_fu_496_p3");
    sc_trace(mVcdFile, zext_ln26_fu_503_p1, "zext_ln26_fu_503_p1");
    sc_trace(mVcdFile, zext_ln28_2_fu_507_p1, "zext_ln28_2_fu_507_p1");
    sc_trace(mVcdFile, add_ln28_2_fu_510_p2, "add_ln28_2_fu_510_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
#endif

    }
}

Loop_memset_AB_proc8::~Loop_memset_AB_proc8() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete A_U;
    delete blockmatmul_mux_4cud_U1;
}

void Loop_memset_AB_proc8::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())) && 
                    esl_seteq<1,1,1>(icmp_ln22_fu_392_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                    esl_seteq<1,1,1>(icmp_ln7_fu_314_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(icmp_ln7_1_fu_320_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln12_fu_326_p1.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                    esl_seteq<1,1,1>(icmp_ln7_fu_314_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(icmp_ln7_1_fu_320_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln12_fu_326_p1.read()))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state9.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state9.read())) {
                ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state9.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter2 = ap_enable_reg_pp1_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter3 = ap_enable_reg_pp1_iter2.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())))) {
            ap_enable_reg_pp1_iter3 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln25_reg_625.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()))) {
        i1_0_reg_267 = select_ln28_1_reg_639.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())))) {
        i1_0_reg_267 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_314_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(icmp_ln7_1_fu_320_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln12_fu_326_p1.read()))) {
        i_0_reg_233 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        i_0_reg_233 = i_reg_571.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln25_fu_424_p2.read()))) {
        indvar_flatten_reg_256 = add_ln25_fu_430_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())))) {
        indvar_flatten_reg_256 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln25_fu_424_p2.read()))) {
        j2_0_reg_278 = j_fu_490_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())))) {
        j2_0_reg_278 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        k_0_reg_245 = k_reg_595.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        k_0_reg_245 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln7_fu_314_p2.read()))) {
        phi_ln7_1_reg_222 = add_ln7_1_fu_308_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        phi_ln7_1_reg_222 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_314_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln7_1_fu_320_p2.read()))) {
        phi_ln7_reg_210 = add_ln7_reg_545.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        phi_ln7_reg_210 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln25_reg_625.read()))) {
        AB_addr_2_reg_660 =  (sc_lv<4>) (zext_ln28_3_fu_516_p1.read());
        tmp_2_reg_671 = tmp_2_fu_521_p6.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)) {
        AB_addr_2_reg_660_pp1_iter2_reg = AB_addr_2_reg_660.read();
        icmp_ln25_reg_625_pp1_iter2_reg = icmp_ln25_reg_625_pp1_iter1_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln25_reg_625.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()))) {
        A_load_reg_666 = A_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln7_reg_545 = add_ln7_fu_289_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_reg_571 = i_fu_335_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln13_reg_567 = icmp_ln13_fu_329_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln25_reg_625 = icmp_ln25_fu_424_p2.read();
        icmp_ln25_reg_625_pp1_iter1_reg = icmp_ln25_reg_625.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())))) {
        k_reg_595 = k_fu_398_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln25_reg_625_pp1_iter1_reg.read()))) {
        mul_ln28_reg_676 = mul_ln28_fu_530_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln25_fu_424_p2.read()))) {
        select_ln28_1_reg_639 = select_ln28_1_fu_456_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln25_fu_424_p2.read()))) {
        select_ln28_reg_634 = select_ln28_fu_448_p3.read();
        trunc_ln28_reg_650 = trunc_ln28_fu_486_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())))) {
        tmp_a_1_05_reg_600 = Bcols_V_a_0_dout.read();
        tmp_a_1_16_reg_605 = Bcols_V_a_1_dout.read();
        tmp_a_1_27_reg_610 = Bcols_V_a_2_dout.read();
        tmp_a_1_38_reg_615 = Bcols_V_a_3_dout.read();
        zext_ln25_reg_620 = zext_ln25_fu_420_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        tmp_a_23_reg_576 = Arows_V_a_2_dout.read();
        tmp_a_34_reg_581 = Arows_V_a_3_dout.read();
        xor_ln17_reg_586 = xor_ln17_fu_364_p2.read();
    }
}

void Loop_memset_AB_proc8::thread_AB_address0() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()))) {
        AB_address0 = AB_addr_2_reg_660.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        AB_address0 =  (sc_lv<4>) (zext_ln7_fu_303_p1.read());
    } else {
        AB_address0 = "XXXX";
    }
}

void Loop_memset_AB_proc8::thread_AB_address1() {
    AB_address1 = AB_addr_2_reg_660_pp1_iter2_reg.read();
}

void Loop_memset_AB_proc8::thread_AB_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         (esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read())))) {
        AB_ce0 = ap_const_logic_1;
    } else {
        AB_ce0 = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_AB_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()))) {
        AB_ce1 = ap_const_logic_1;
    } else {
        AB_ce1 = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_AB_d0() {
    AB_d0 = ap_const_lv32_0;
}

void Loop_memset_AB_proc8::thread_AB_d1() {
    AB_d1 = (!mul_ln28_reg_676.read().is_01() || !AB_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln28_reg_676.read()) + sc_biguint<32>(AB_q0.read()));
}

void Loop_memset_AB_proc8::thread_AB_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        AB_we0 = ap_const_logic_1;
    } else {
        AB_we0 = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_AB_we1() {
    if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln25_reg_625_pp1_iter2_reg.read()))) {
        AB_we1 = ap_const_logic_1;
    } else {
        AB_we1 = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_A_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        A_address0 =  (sc_lv<5>) (zext_ln28_1_fu_481_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        A_address0 =  (sc_lv<5>) (tmp_6_fu_375_p3.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        A_address0 =  (sc_lv<5>) (zext_ln17_fu_359_p1.read());
    } else {
        A_address0 =  (sc_lv<5>) ("XXXXX");
    }
}

void Loop_memset_AB_proc8::thread_A_address1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        A_address1 =  (sc_lv<5>) (zext_ln17_2_fu_387_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        A_address1 =  (sc_lv<5>) (zext_ln17_1_fu_370_p1.read());
    } else {
        A_address1 =  (sc_lv<5>) ("XXXXX");
    }
}

void Loop_memset_AB_proc8::thread_A_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)))) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_A_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)))) {
        A_ce1 = ap_const_logic_1;
    } else {
        A_ce1 = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_A_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        A_d0 = tmp_a_23_reg_576.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        A_d0 = Arows_V_a_0_dout.read();
    } else {
        A_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Loop_memset_AB_proc8::thread_A_d1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        A_d1 = tmp_a_34_reg_581.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        A_d1 = Arows_V_a_1_dout.read();
    } else {
        A_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Loop_memset_AB_proc8::thread_A_we0() {
    if (((esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)))) {
        A_we0 = ap_const_logic_1;
    } else {
        A_we0 = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_A_we1() {
    if (((esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)))) {
        A_we1 = ap_const_logic_1;
    } else {
        A_we1 = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_Arows_V_a_0_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0))) {
        Arows_V_a_0_blk_n = Arows_V_a_0_empty_n.read();
    } else {
        Arows_V_a_0_blk_n = ap_const_logic_1;
    }
}

void Loop_memset_AB_proc8::thread_Arows_V_a_0_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        Arows_V_a_0_read = ap_const_logic_1;
    } else {
        Arows_V_a_0_read = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_Arows_V_a_1_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0))) {
        Arows_V_a_1_blk_n = Arows_V_a_1_empty_n.read();
    } else {
        Arows_V_a_1_blk_n = ap_const_logic_1;
    }
}

void Loop_memset_AB_proc8::thread_Arows_V_a_1_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        Arows_V_a_1_read = ap_const_logic_1;
    } else {
        Arows_V_a_1_read = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_Arows_V_a_2_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0))) {
        Arows_V_a_2_blk_n = Arows_V_a_2_empty_n.read();
    } else {
        Arows_V_a_2_blk_n = ap_const_logic_1;
    }
}

void Loop_memset_AB_proc8::thread_Arows_V_a_2_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        Arows_V_a_2_read = ap_const_logic_1;
    } else {
        Arows_V_a_2_read = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_Arows_V_a_3_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0))) {
        Arows_V_a_3_blk_n = Arows_V_a_3_empty_n.read();
    } else {
        Arows_V_a_3_blk_n = ap_const_logic_1;
    }
}

void Loop_memset_AB_proc8::thread_Arows_V_a_3_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        Arows_V_a_3_read = ap_const_logic_1;
    } else {
        Arows_V_a_3_read = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_Bcols_V_a_0_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()))) {
        Bcols_V_a_0_blk_n = Bcols_V_a_0_empty_n.read();
    } else {
        Bcols_V_a_0_blk_n = ap_const_logic_1;
    }
}

void Loop_memset_AB_proc8::thread_Bcols_V_a_0_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())))) {
        Bcols_V_a_0_read = ap_const_logic_1;
    } else {
        Bcols_V_a_0_read = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_Bcols_V_a_1_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()))) {
        Bcols_V_a_1_blk_n = Bcols_V_a_1_empty_n.read();
    } else {
        Bcols_V_a_1_blk_n = ap_const_logic_1;
    }
}

void Loop_memset_AB_proc8::thread_Bcols_V_a_1_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())))) {
        Bcols_V_a_1_read = ap_const_logic_1;
    } else {
        Bcols_V_a_1_read = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_Bcols_V_a_2_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()))) {
        Bcols_V_a_2_blk_n = Bcols_V_a_2_empty_n.read();
    } else {
        Bcols_V_a_2_blk_n = ap_const_logic_1;
    }
}

void Loop_memset_AB_proc8::thread_Bcols_V_a_2_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())))) {
        Bcols_V_a_2_read = ap_const_logic_1;
    } else {
        Bcols_V_a_2_read = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_Bcols_V_a_3_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()))) {
        Bcols_V_a_3_blk_n = Bcols_V_a_3_empty_n.read();
    } else {
        Bcols_V_a_3_blk_n = ap_const_logic_1;
    }
}

void Loop_memset_AB_proc8::thread_Bcols_V_a_3_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())))) {
        Bcols_V_a_3_read = ap_const_logic_1;
    } else {
        Bcols_V_a_3_read = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_add_ln25_fu_430_p2() {
    add_ln25_fu_430_p2 = (!indvar_flatten_reg_256.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(indvar_flatten_reg_256.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void Loop_memset_AB_proc8::thread_add_ln28_1_fu_476_p2() {
    add_ln28_1_fu_476_p2 = (!zext_ln28_fu_472_p1.read().is_01() || !zext_ln25_reg_620.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln28_fu_472_p1.read()) + sc_biguint<7>(zext_ln25_reg_620.read()));
}

void Loop_memset_AB_proc8::thread_add_ln28_2_fu_510_p2() {
    add_ln28_2_fu_510_p2 = (!zext_ln26_fu_503_p1.read().is_01() || !zext_ln28_2_fu_507_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln26_fu_503_p1.read()) + sc_biguint<6>(zext_ln28_2_fu_507_p1.read()));
}

void Loop_memset_AB_proc8::thread_add_ln7_1_fu_308_p2() {
    add_ln7_1_fu_308_p2 = (!phi_ln7_1_reg_222.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(phi_ln7_1_reg_222.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void Loop_memset_AB_proc8::thread_add_ln7_fu_289_p2() {
    add_ln7_fu_289_p2 = (!phi_ln7_reg_210.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(phi_ln7_reg_210.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void Loop_memset_AB_proc8::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[3];
}

void Loop_memset_AB_proc8::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[4];
}

void Loop_memset_AB_proc8::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[7];
}

void Loop_memset_AB_proc8::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Loop_memset_AB_proc8::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[8];
}

void Loop_memset_AB_proc8::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Loop_memset_AB_proc8::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void Loop_memset_AB_proc8::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[5];
}

void Loop_memset_AB_proc8::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[6];
}

void Loop_memset_AB_proc8::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op49.read()));
}

void Loop_memset_AB_proc8::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op49.read()));
}

void Loop_memset_AB_proc8::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Loop_memset_AB_proc8::thread_ap_block_state10_pp1_stage0_iter1() {
    ap_block_state10_pp1_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_block_state11_pp1_stage0_iter2() {
    ap_block_state11_pp1_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_block_state12_pp1_stage0_iter3() {
    ap_block_state12_pp1_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_block_state4_pp0_stage0_iter0() {
    ap_block_state4_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_block_state5_pp0_stage1_iter0() {
    ap_block_state5_pp0_stage1_iter0 = (esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op49.read()));
}

void Loop_memset_AB_proc8::thread_ap_block_state6_pp0_stage0_iter1() {
    ap_block_state6_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_block_state8() {
    ap_block_state8 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read()));
}

void Loop_memset_AB_proc8::thread_ap_block_state9_pp1_stage0_iter0() {
    ap_block_state9_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Loop_memset_AB_proc8::thread_ap_condition_pp0_exit_iter0_state4() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln13_fu_329_p2.read())) {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_ap_condition_pp1_exit_iter0_state9() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln25_fu_424_p2.read())) {
        ap_condition_pp1_exit_iter0_state9 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state9 = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())) && 
         esl_seteq<1,1,1>(icmp_ln22_fu_392_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Loop_memset_AB_proc8::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void Loop_memset_AB_proc8::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void Loop_memset_AB_proc8::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter3.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_ap_phi_mux_i1_0_phi_fu_271_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln25_reg_625.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i1_0_phi_fu_271_p4 = select_ln28_1_reg_639.read();
    } else {
        ap_phi_mux_i1_0_phi_fu_271_p4 = i1_0_reg_267.read();
    }
}

void Loop_memset_AB_proc8::thread_ap_phi_mux_i_0_phi_fu_237_p4() {
    if ((esl_seteq<1,1,1>(icmp_ln13_reg_567.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i_0_phi_fu_237_p4 = i_reg_571.read();
    } else {
        ap_phi_mux_i_0_phi_fu_237_p4 = i_0_reg_233.read();
    }
}

void Loop_memset_AB_proc8::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())) && 
         esl_seteq<1,1,1>(icmp_ln22_fu_392_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Loop_memset_AB_proc8::thread_i_1_fu_436_p2() {
    i_1_fu_436_p2 = (!ap_const_lv3_1.is_01() || !ap_phi_mux_i1_0_phi_fu_271_p4.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(ap_phi_mux_i1_0_phi_fu_271_p4.read()));
}

void Loop_memset_AB_proc8::thread_i_fu_335_p2() {
    i_fu_335_p2 = (!ap_phi_mux_i_0_phi_fu_237_p4.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(ap_phi_mux_i_0_phi_fu_237_p4.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void Loop_memset_AB_proc8::thread_icmp_ln13_fu_329_p2() {
    icmp_ln13_fu_329_p2 = (!ap_phi_mux_i_0_phi_fu_237_p4.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i_0_phi_fu_237_p4.read() == ap_const_lv4_8);
}

void Loop_memset_AB_proc8::thread_icmp_ln22_fu_392_p2() {
    icmp_ln22_fu_392_p2 = (!k_0_reg_245.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_245.read() == ap_const_lv4_8);
}

void Loop_memset_AB_proc8::thread_icmp_ln25_fu_424_p2() {
    icmp_ln25_fu_424_p2 = (!indvar_flatten_reg_256.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_256.read() == ap_const_lv5_10);
}

void Loop_memset_AB_proc8::thread_icmp_ln26_fu_442_p2() {
    icmp_ln26_fu_442_p2 = (!j2_0_reg_278.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(j2_0_reg_278.read() == ap_const_lv3_4);
}

void Loop_memset_AB_proc8::thread_icmp_ln7_1_fu_320_p2() {
    icmp_ln7_1_fu_320_p2 = (!phi_ln7_reg_210.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(phi_ln7_reg_210.read() == ap_const_lv2_3);
}

void Loop_memset_AB_proc8::thread_icmp_ln7_fu_314_p2() {
    icmp_ln7_fu_314_p2 = (!phi_ln7_1_reg_222.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(phi_ln7_1_reg_222.read() == ap_const_lv2_3);
}

void Loop_memset_AB_proc8::thread_io_acc_block_signal_op49() {
    io_acc_block_signal_op49 = (Arows_V_a_0_empty_n.read() & Arows_V_a_1_empty_n.read() & Arows_V_a_2_empty_n.read() & Arows_V_a_3_empty_n.read());
}

void Loop_memset_AB_proc8::thread_io_acc_block_signal_op82() {
    io_acc_block_signal_op82 = (Bcols_V_a_0_empty_n.read() & Bcols_V_a_1_empty_n.read() & Bcols_V_a_2_empty_n.read() & Bcols_V_a_3_empty_n.read());
}

void Loop_memset_AB_proc8::thread_j_fu_490_p2() {
    j_fu_490_p2 = (!ap_const_lv3_1.is_01() || !select_ln28_fu_448_p3.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(select_ln28_fu_448_p3.read()));
}

void Loop_memset_AB_proc8::thread_k_fu_398_p2() {
    k_fu_398_p2 = (!k_0_reg_245.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k_0_reg_245.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void Loop_memset_AB_proc8::thread_mul_ln28_fu_530_p2() {
    mul_ln28_fu_530_p2 = (!tmp_2_reg_671.read().is_01() || !A_load_reg_666.read().is_01())? sc_lv<32>(): sc_bigint<32>(tmp_2_reg_671.read()) * sc_bigint<32>(A_load_reg_666.read());
}

void Loop_memset_AB_proc8::thread_select_ln28_1_fu_456_p3() {
    select_ln28_1_fu_456_p3 = (!icmp_ln26_fu_442_p2.read()[0].is_01())? sc_lv<3>(): ((icmp_ln26_fu_442_p2.read()[0].to_bool())? i_1_fu_436_p2.read(): ap_phi_mux_i1_0_phi_fu_271_p4.read());
}

void Loop_memset_AB_proc8::thread_select_ln28_fu_448_p3() {
    select_ln28_fu_448_p3 = (!icmp_ln26_fu_442_p2.read()[0].is_01())? sc_lv<3>(): ((icmp_ln26_fu_442_p2.read()[0].to_bool())? ap_const_lv3_0: j2_0_reg_278.read());
}

void Loop_memset_AB_proc8::thread_sext_ln17_fu_384_p1() {
    sext_ln17_fu_384_p1 = esl_sext<5,4>(xor_ln17_reg_586.read());
}

void Loop_memset_AB_proc8::thread_tmp_5_fu_295_p3() {
    tmp_5_fu_295_p3 = esl_concat<2,2>(phi_ln7_reg_210.read(), phi_ln7_1_reg_222.read());
}

void Loop_memset_AB_proc8::thread_tmp_6_fu_375_p3() {
    tmp_6_fu_375_p3 = esl_concat<60,4>(ap_const_lv60_1, i_0_reg_233.read());
}

void Loop_memset_AB_proc8::thread_tmp_7_fu_464_p3() {
    tmp_7_fu_464_p3 = esl_concat<3,3>(select_ln28_1_fu_456_p3.read(), ap_const_lv3_0);
}

void Loop_memset_AB_proc8::thread_tmp_8_fu_496_p3() {
    tmp_8_fu_496_p3 = esl_concat<3,2>(select_ln28_1_reg_639.read(), ap_const_lv2_0);
}

void Loop_memset_AB_proc8::thread_trunc_ln12_fu_326_p1() {
    trunc_ln12_fu_326_p1 = it.read().range(1-1, 0);
}

void Loop_memset_AB_proc8::thread_trunc_ln28_fu_486_p1() {
    trunc_ln28_fu_486_p1 = select_ln28_fu_448_p3.read().range(2-1, 0);
}

void Loop_memset_AB_proc8::thread_xor_ln17_fu_364_p2() {
    xor_ln17_fu_364_p2 = (i_0_reg_233.read() ^ ap_const_lv4_8);
}

void Loop_memset_AB_proc8::thread_zext_ln17_1_fu_370_p1() {
    zext_ln17_1_fu_370_p1 = esl_zext<64,4>(xor_ln17_fu_364_p2.read());
}

void Loop_memset_AB_proc8::thread_zext_ln17_2_fu_387_p1() {
    zext_ln17_2_fu_387_p1 = esl_zext<64,5>(sext_ln17_fu_384_p1.read());
}

void Loop_memset_AB_proc8::thread_zext_ln17_fu_359_p1() {
    zext_ln17_fu_359_p1 = esl_zext<64,4>(i_0_reg_233.read());
}

void Loop_memset_AB_proc8::thread_zext_ln25_fu_420_p1() {
    zext_ln25_fu_420_p1 = esl_zext<7,4>(k_0_reg_245.read());
}

void Loop_memset_AB_proc8::thread_zext_ln26_fu_503_p1() {
    zext_ln26_fu_503_p1 = esl_zext<6,5>(tmp_8_fu_496_p3.read());
}

void Loop_memset_AB_proc8::thread_zext_ln28_1_fu_481_p1() {
    zext_ln28_1_fu_481_p1 = esl_zext<64,7>(add_ln28_1_fu_476_p2.read());
}

void Loop_memset_AB_proc8::thread_zext_ln28_2_fu_507_p1() {
    zext_ln28_2_fu_507_p1 = esl_zext<6,3>(select_ln28_reg_634.read());
}

void Loop_memset_AB_proc8::thread_zext_ln28_3_fu_516_p1() {
    zext_ln28_3_fu_516_p1 = esl_zext<64,6>(add_ln28_2_fu_510_p2.read());
}

void Loop_memset_AB_proc8::thread_zext_ln28_fu_472_p1() {
    zext_ln28_fu_472_p1 = esl_zext<7,6>(tmp_7_fu_464_p3.read());
}

void Loop_memset_AB_proc8::thread_zext_ln7_fu_303_p1() {
    zext_ln7_fu_303_p1 = esl_zext<64,4>(tmp_5_fu_295_p3.read());
}

void Loop_memset_AB_proc8::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln7_fu_314_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_ln7_1_fu_320_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln12_fu_326_p1.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln7_fu_314_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_ln7_1_fu_320_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln12_fu_326_p1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln7_fu_314_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln7_1_fu_320_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln13_fu_329_p2.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln13_fu_329_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())) && esl_seteq<1,1,1>(icmp_ln22_fu_392_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_392_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op82.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((!(esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter2.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln25_fu_424_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if (((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter3.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter2.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln25_fu_424_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

